#!/bin/sh
set -eu

# 01_full_schema.sql is a staging schema dump generated by a newer pg_dump.
# PostgreSQL 16 cannot parse transaction_timeout, so filter only that
# compatibility line at container initialization time without editing the dump.
sed '/^SET transaction_timeout = 0;$/d' /schema/01_full_schema.sql > /tmp/01_full_schema_pg16.sql
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" \
  -f /tmp/01_full_schema_pg16.sql
