#!/usr/bin/env bash
set -euo pipefail

# 01_full_schema.sql is a staging schema dump generated by a newer pg_dump.
# PostgreSQL 16 cannot parse transaction_timeout, so filter only that
# compatibility line at container initialization time without editing the dump.
grep -v '^SET transaction_timeout = 0;$' /schema/01_full_schema.sql \
  | psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB"
