CREATE TYPE "user_artist_status" AS ENUM (
  'accept',
  'reject',
  'check'
);

CREATE TYPE "offer_status" AS ENUM (
  'applied',
  'rejected',
  'ongoing',
  'suspend',
  'finished',
  'canceled'
);

CREATE TYPE "user_status" AS ENUM (
  'invited',
  'rejected',
  'joined'
);

CREATE TYPE "user_category" AS ENUM (
  'musician',
  'curator',
  'creator',
  'supporter'
);

CREATE TYPE "user_role" AS ENUM (
  'admin',
  'member'
);

CREATE TYPE "artist_status" AS ENUM (
  'visible',
  'hidden',
  'unknown'
);

CREATE TYPE "purchase_status" AS ENUM (
  'success',
  'fail',
  'pending'
);

CREATE TYPE "offer_category" AS ENUM (
  'creation',
  'event',
  'promotion',
  'other'
);

CREATE TYPE "message_room_type" AS ENUM (
  'dm',
  'group'
);

CREATE TABLE "users" (
  "id" varchar(28) PRIMARY KEY NOT NULL,
  "id_token" varchar,
  "fcm_token" varchar,
  "username" varchar NOT NULL,
  "realname" varchar NOT NULL,
  "email" varchar NOT NULL,
  "img_url" varchar,
  "evm_addr" varchar,
  "status" user_status NOT NULL DEFAULT 'invited',
  "invited_by" varchar(28),
  "fsp" int NOT NULL DEFAULT 1,
  "fsp_temp" int NOT NULL DEFAULT 0,
  "credential" int NOT NULL DEFAULT 0,
  "category" user_category NOT NULL,
  "primary_category" user_category NOT NULL,
  "is_superadmin" bool DEFAULT false,
  "publicity" bool NOT NULL DEFAULT 'true',
  "greeting" varchar,
  "skill" varchar,
  "x_handle" varchar,
  "instagram_handle" varchar,
  "fb_handle" varchar,
  "interest_offer" offer_category,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  "last_login_at" timestamp
);

CREATE TABLE "portfolios" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" varchar(28) NOT NULL,
  "title" varchar NOT NULL,
  "description" varchar NOT NULL,
  "img_url" varchar,
  "category" varchar NOT NULL,
  "release_date" date,
  "external_url" varchar,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "maps" (
  "id" uuid PRIMARY KEY NOT NULL DEFAULT (gen_random_uuid()),
  "following_user_id" varchar(28) NOT NULL,
  "followed_user_id" varchar(28) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "invitations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "invitee" varchar(28) NOT NULL,
  "inviter_email" varchar NOT NULL,
  "digest_code" varchar,
  "invited_at" timestamp NOT NULL DEFAULT (now()),
  "is_joined" bool NOT NULL DEFAULT 'false',
  "joined_email" varchar,
  "joined_at" timestamp
);

CREATE TABLE "txs_fsp" (
  "id" uuid PRIMARY KEY NOT NULL DEFAULT (gen_random_uuid()),
  "from" varchar(28),
  "to" varchar(28) NOT NULL,
  "amount" int NOT NULL DEFAULT 0,
  "tx_at" timestamp NOT NULL DEFAULT (now()),
  "notes" varchar
);

CREATE TABLE "purchase_history" (
  "purchase_id" uuid PRIMARY KEY NOT NULL DEFAULT (gen_random_uuid()),
  "event_id" int,
  "user_id" varchar(28) NOT NULL,
  "amount" int NOT NULL DEFAULT 0,
  "payment_method" varchar,
  "status" purchase_status,
  "timestamp" timestamp NOT NULL DEFAULT (now()),
  "stripe_payment_intent_id" varchar
);

CREATE TABLE "webhook_stripe" (
  "event_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "payload" json,
  "timestamp" timestamp NOT NULL DEFAULT (now()),
  "processed" bool NOT NULL DEFAULT 'false'
);

CREATE TABLE "prizes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "img_url" varchar,
  "name" varchar NOT NULL,
  "point" int NOT NULL,
  "description" varchar NOT NULL,
  "representation" varchar(28) NOT NULL,
  "condition" varchar,
  "publicity" bool NOT NULL DEFAULT 'true'
);

CREATE TABLE "exchange_prize_history" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "prize_id" int NOT NULL,
  "user" varchar(28) NOT NULL,
  "point_used" int NOT NULL,
  "amount" int NOT NULL DEFAULT 1,
  "exchanged_at" timestamp NOT NULL DEFAULT (now()),
  "is_used" bool NOT NULL DEFAULT 'false',
  "used_at" timestamp
);

CREATE TABLE "quests" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar NOT NULL,
  "description" varchar NOT NULL,
  "category" varchar,
  "point" int NOT NULL DEFAULT 0,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "quest_user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user" varchar(28) NOT NULL,
  "quest" int NOT NULL,
  "is_done" bool NOT NULL DEFAULT 'false'
);

CREATE TABLE "offers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "raid_id" int,
  "owner" varchar(28) NOT NULL,
  "title" varchar NOT NULL,
  "description" varchar NOT NULL,
  "deadline" varchar,
  "place" varchar NOT NULL,
  "attention" varchar,
  "required_skill" varchar,
  "target_role" user_category,
  "img_url" varchar,
  "publicity" bool NOT NULL DEFAULT 'true',
  "category" offer_category,
  "fee" int NOT NULL DEFAULT 0,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "offer_attach" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "offer_id" int NOT NULL,
  "file_uri" varchar,
  "image_uri" varchar
);

CREATE TABLE "offer_user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "offer_id" int NOT NULL,
  "user_id" varchar(28) NOT NULL,
  "status" offer_status NOT NULL
);

CREATE TABLE "raids" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "owner" varchar(28) NOT NULL,
  "title" varchar NOT NULL,
  "description" varchar NOT NULL,
  "category" offer_category NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "comments" (
  "id" int PRIMARY KEY NOT NULL,
  "commented_user_id" varchar(28) NOT NULL,
  "offer_id" int NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "content" varchar NOT NULL
);

CREATE TABLE "news" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "contents" text NOT NULL,
  "user_id" varchar(28),
  "category" varchar,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "notifications" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "title" varchar NOT NULL,
  "content" varchar NOT NULL,
  "category" varchar DEFAULT 'info',
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "notification_user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "notification_id" int NOT NULL,
  "user" varchar(28) NOT NULL,
  "is_read" bool NOT NULL DEFAULT 'false',
  "is_deleted" bool NOT NULL DEFAULT 'false'
);

CREATE TABLE "favorites" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "user_id" varchar(28) NOT NULL,
  "liked_by" varchar(28) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "short_notes" (
  "id" uuid PRIMARY KEY NOT NULL DEFAULT (gen_random_uuid()),
  "writer" varchar(28) NOT NULL,
  "to_user" varchar(28) NOT NULL,
  "comment" varchar(140) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "artists" (
  "id" uuid PRIMARY KEY NOT NULL DEFAULT (gen_random_uuid()),
  "artist_id" varchar(28) UNIQUE NOT NULL,
  "display_name_jp" varchar NOT NULL,
  "display_name_en" varchar NOT NULL,
  "display_name_kana" varchar,
  "img_url" varchar,
  "fsp" int NOT NULL DEFAULT 0,
  "status" artist_status NOT NULL,
  "since" date,
  "universal_id" varchar,
  "apple_key" varchar,
  "spotify_key" varchar,
  "line_key" varchar,
  "amazon_key" varchar,
  "youtube_key" varchar
);

CREATE TABLE "user_artist" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" varchar(28) NOT NULL,
  "artist_id" varchar(28) NOT NULL,
  "is_admin" bool NOT NULL DEFAULT 'false',
  "status" user_artist_status NOT NULL DEFAULT 'check'
);

CREATE TABLE "products" (
  "upc" varchar PRIMARY KEY NOT NULL,
  "title" varchar NOT NULL,
  "img_url" varchar,
  "type" varchar,
  "distributed_at" date,
  "artist_id" varchar(28)
);

CREATE TABLE "tracks" (
  "isrc" varchar PRIMARY KEY NOT NULL,
  "img_url" varchar,
  "title" varchar NOT NULL,
  "artist_id" varchar(28)
);

CREATE TABLE "product_track" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "upc" varchar NOT NULL,
  "isrc" varchar NOT NULL,
  "track_no" int
);

CREATE TABLE "track_credits" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "isrc" varchar NOT NULL,
  "commit_user" varchar(28) NOT NULL,
  "credit_role" varchar NOT NULL,
  "credit_name" varchar NOT NULL,
  "credit_user" varchar(28),
  "email" varchar NOT NULL,
  "is_invite" bool,
  "memo" varchar,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "plays_daily" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "isrc" varchar,
  "date" date,
  "spotify" int NOT NULL DEFAULT 0,
  "apple" int NOT NULL DEFAULT 0,
  "line" int NOT NULL DEFAULT 0,
  "amazon" int DEFAULT 0,
  "youtube" int DEFAULT 0,
  "sum" int
);

CREATE TABLE "plays_monthly" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "isrc" varchar,
  "month" date,
  "spotify" int NOT NULL DEFAULT 0,
  "apple" int NOT NULL DEFAULT 0,
  "line" int NOT NULL DEFAULT 0,
  "amazon" int NOT NULL DEFAULT 0,
  "youtube" int NOT NULL DEFAULT 0,
  "sum" int
);

CREATE TABLE "plays_yearly" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "isrc" varchar,
  "year" varchar,
  "spotify" int NOT NULL DEFAULT 0,
  "apple" int NOT NULL DEFAULT 0,
  "line" int NOT NULL DEFAULT 0,
  "amazon" int NOT NULL DEFAULT 0,
  "youtube" int NOT NULL DEFAULT 0,
  "sum" int
);

CREATE TABLE "gender_gen_playback" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "isrc" varchar NOT NULL,
  "date" date NOT NULL,
  "gender" varchar,
  "age" varchar,
  "play_count" int NOT NULL DEFAULT 0
);

CREATE TABLE "indicators" (
  "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar NOT NULL,
  "description" varchar(140),
  "logic" varchar NOT NULL
);

CREATE TABLE "messages" (
  "id" uuid PRIMARY KEY NOT NULL DEFAULT (gen_random_uuid()),
  "room_id" uuid NOT NULL,
  "send_by" varchar(28) NOT NULL,
  "message" varchar NOT NULL DEFAULT '',
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "message_attach" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "sender" varchar(28),
  "message_id" uuid,
  "attached_img_url" varchar,
  "attached_file_url" varchar,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "rooms" (
  "id" uuid PRIMARY KEY NOT NULL DEFAULT (gen_random_uuid()),
  "type" message_room_type NOT NULL DEFAULT 'dm',
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "latest_sent_at" timestamp,
  "latest_message_id" uuid,
  "latest_message" varchar
);

CREATE TABLE "room_user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "room_id" uuid NOT NULL,
  "user_id" varchar(28) NOT NULL,
  "last_read_message_id" uuid
);

CREATE TABLE "user_report" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "reported_user_id" varchar(28) NOT NULL,
  "reporter_user_id" varchar(28) NOT NULL,
  "report_content" varchar NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "user_blocks" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "blocked_user_id" varchar(28) NOT NULL,
  "blocker_user_id" varchar(28) NOT NULL,
  "is_solved" bool NOT NULL DEFAULT 'false',
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "offer_report" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "offer_id" int NOT NULL,
  "reporter_user_id" varchar(28) NOT NULL,
  "report_content" varchar NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "release_report" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "release" varchar NOT NULL,
  "reporter_user_id" varchar(28) NOT NULL,
  "report_content" varchar NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE INDEX ON "users" ("evm_addr");

CREATE INDEX ON "exchange_prize_history" ("user", "is_used");

CREATE INDEX ON "portfolios" ("user_id");

CREATE INDEX ON "maps" ("id");

CREATE INDEX ON "maps" ("followed_user_id", "following_user_id");

CREATE INDEX ON "txs_fsp" ("from");

CREATE INDEX ON "txs_fsp" ("to");

CREATE INDEX ON "txs_fsp" ("id", "tx_at");

CREATE INDEX ON "prizes" ("representation");

CREATE INDEX ON "quest_user" ("user", "quest");

CREATE INDEX ON "offers" ("owner");

CREATE INDEX ON "offer_user" ("offer_id", "user_id");

CREATE INDEX ON "raids" ("owner");

CREATE INDEX ON "comments" ("commented_user_id");

CREATE INDEX ON "comments" ("offer_id");

CREATE INDEX ON "notification_user" ("user", "notification_id");

CREATE INDEX ON "favorites" ("user_id");

CREATE INDEX ON "favorites" ("liked_by");

CREATE INDEX ON "short_notes" ("id", "created_at");

CREATE INDEX ON "artists" ("artist_id");

CREATE INDEX ON "user_artist" ("id");

CREATE INDEX ON "user_artist" ("user_id", "artist_id");

CREATE INDEX ON "product_track" ("id");

CREATE INDEX ON "product_track" ("upc", "isrc");

CREATE INDEX ON "track_credits" ("isrc");

CREATE INDEX ON "plays_daily" ("isrc", "date");

CREATE INDEX ON "plays_monthly" ("isrc", "month");

CREATE INDEX ON "plays_yearly" ("isrc", "year");

CREATE INDEX ON "gender_gen_playback" ("isrc", "date");

CREATE INDEX ON "messages" ("room_id");

CREATE INDEX ON "messages" ("send_by");

CREATE INDEX ON "room_user" ("room_id", "user_id");

COMMENT ON COLUMN "users"."id_token" IS 'Token from firebase auth';

COMMENT ON COLUMN "txs_fsp"."notes" IS '摘要';

COMMENT ON COLUMN "prizes"."condition" IS '条件（月件までなど）';

COMMENT ON COLUMN "artists"."img_url" IS 'JAN code';

ALTER TABLE "purchase_history" ADD FOREIGN KEY ("event_id") REFERENCES "webhook_stripe" ("event_id");

ALTER TABLE "user_blocks" ADD FOREIGN KEY ("blocked_user_id") REFERENCES "users" ("id");

ALTER TABLE "user_blocks" ADD FOREIGN KEY ("blocker_user_id") REFERENCES "users" ("id");

ALTER TABLE "portfolios" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "exchange_prize_history" ADD FOREIGN KEY ("prize_id") REFERENCES "prizes" ("id");

ALTER TABLE "offers" ADD FOREIGN KEY ("raid_id") REFERENCES "raids" ("id");

ALTER TABLE "offer_attach" ADD FOREIGN KEY ("offer_id") REFERENCES "offers" ("id");

ALTER TABLE "offer_user" ADD FOREIGN KEY ("offer_id") REFERENCES "offers" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("offer_id") REFERENCES "offers" ("id");

ALTER TABLE "news" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "notification_user" ADD FOREIGN KEY ("notification_id") REFERENCES "notifications" ("id");

ALTER TABLE "user_artist" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_artist" ADD FOREIGN KEY ("artist_id") REFERENCES "artists" ("artist_id");

ALTER TABLE "products" ADD FOREIGN KEY ("artist_id") REFERENCES "artists" ("artist_id");

ALTER TABLE "tracks" ADD FOREIGN KEY ("artist_id") REFERENCES "artists" ("artist_id");

ALTER TABLE "product_track" ADD FOREIGN KEY ("upc") REFERENCES "products" ("upc");

ALTER TABLE "product_track" ADD FOREIGN KEY ("isrc") REFERENCES "tracks" ("isrc");

ALTER TABLE "track_credits" ADD FOREIGN KEY ("isrc") REFERENCES "tracks" ("isrc");

ALTER TABLE "plays_daily" ADD FOREIGN KEY ("isrc") REFERENCES "tracks" ("isrc");

ALTER TABLE "plays_monthly" ADD FOREIGN KEY ("isrc") REFERENCES "tracks" ("isrc");

ALTER TABLE "plays_yearly" ADD FOREIGN KEY ("isrc") REFERENCES "tracks" ("isrc");

ALTER TABLE "messages" ADD FOREIGN KEY ("room_id") REFERENCES "rooms" ("id");

ALTER TABLE "message_attach" ADD FOREIGN KEY ("message_id") REFERENCES "messages" ("id");

ALTER TABLE "rooms" ADD FOREIGN KEY ("latest_message_id") REFERENCES "messages" ("id");

ALTER TABLE "room_user" ADD FOREIGN KEY ("room_id") REFERENCES "rooms" ("id");

ALTER TABLE "maps" ADD FOREIGN KEY ("following_user_id") REFERENCES "users" ("id");

ALTER TABLE "maps" ADD FOREIGN KEY ("followed_user_id") REFERENCES "users" ("id");

ALTER TABLE "messages" ADD FOREIGN KEY ("send_by") REFERENCES "users" ("id");

ALTER TABLE "room_user" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "txs_fsp" ADD FOREIGN KEY ("to") REFERENCES "users" ("id");

ALTER TABLE "txs_fsp" ADD FOREIGN KEY ("from") REFERENCES "users" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("commented_user_id") REFERENCES "users" ("id");

ALTER TABLE "favorites" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "favorites" ADD FOREIGN KEY ("liked_by") REFERENCES "users" ("id");

ALTER TABLE "offers" ADD FOREIGN KEY ("owner") REFERENCES "users" ("id");

ALTER TABLE "offer_user" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "raids" ADD FOREIGN KEY ("owner") REFERENCES "users" ("id");

ALTER TABLE "purchase_history" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "prizes" ADD FOREIGN KEY ("representation") REFERENCES "users" ("id");

ALTER TABLE "exchange_prize_history" ADD FOREIGN KEY ("user") REFERENCES "users" ("id");

ALTER TABLE "notification_user" ADD FOREIGN KEY ("user") REFERENCES "users" ("id");

ALTER TABLE "invitations" ADD FOREIGN KEY ("invitee") REFERENCES "users" ("id");

ALTER TABLE "track_credits" ADD FOREIGN KEY ("commit_user") REFERENCES "users" ("id");
