CREATE TYPE "offer_status" AS ENUM (
  'ongoing',
  'suspend',
  'finished'
);

CREATE TYPE "user_status" AS ENUM (
  'invited',
  'rejected',
  'joined'
);

CREATE TYPE "user_role" AS ENUM (
  'musician',
  'curator',
  'other'
);

CREATE TYPE "artist_status" AS ENUM (
  'visible',
  'hidden',
  'unknown'
);

CREATE TYPE "purchase_status" AS ENUM (
  'success',
  'fail',
  'pending'
);

CREATE TABLE "users" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "username" varchar NOT NULL,
  "role" user_role,
  "evm_addr" varchar,
  "status" user_status,
  "invited_by" uuid,
  "fsp" int,
  "credential" int,
  "update_at" timestamp,
  "created_at" timestamp
);

CREATE TABLE "maps" (
  "following_user_id" uuid,
  "followed_user_id" uuid,
  "status" bool,
  "created_at" timestamp,
  PRIMARY KEY ("followed_user_id", "following_user_id")
);

CREATE TABLE "txs_fsp" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "from" uuid,
  "to" uuid,
  "amount" int,
  "tx_at" timestamp
);

CREATE TABLE "purchase_history" (
  "purchase_id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "event_id" int,
  "user_id" uuid,
  "product_id" varchar,
  "amount" int,
  "currency" int,
  "payment_method" varchar,
  "status" purchase_status,
  "timestamp" timestamp,
  "stripe_payment_intent_id" varchar
);

CREATE TABLE "webhook_stripe" (
  "event_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "payload" json,
  "timestamp" timestamp,
  "processed" bool
);

CREATE TABLE "webhook_clerk" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "payload" json,
  "timestamp" timestamp,
  "processed" bool
);

CREATE TABLE "quests" (
  "id" ulid PRIMARY KEY DEFAULT (gen_ulid()),
  "name" varchar,
  "description" varchar
);

CREATE TABLE "offers" (
  "id" ulid PRIMARY KEY DEFAULT (gen_ulid()),
  "raid_id" ulid,
  "owner" uuid,
  "release_dt" date,
  "title" varchar,
  "description" varchar,
  "category" varchar
);

CREATE TABLE "raids" (
  "id" ulid PRIMARY KEY DEFAULT (gen_ulid()),
  "owner" uuid,
  "title" varchar
);

CREATE TABLE "comments" (
  "id" ulid PRIMARY KEY DEFAULT (gen_ulid()),
  "user_id" uuid,
  "offer_id" ulid,
  "created_at" timestamp
);

CREATE TABLE "news" (
  "id" ulid PRIMARY KEY DEFAULT (gen_ulid()),
  "title" varchar,
  "body" text,
  "user_id" uuid,
  "category" varchar,
  "created_at" timestamp
);

CREATE TABLE "notifications" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar,
  "content" varchar
);

CREATE TABLE "favorites" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "user_id" uuid,
  "liked_by" uuid
);

CREATE TABLE "short_notes" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "favorite_id" uuid,
  "comment" varchar(140)
);

CREATE TABLE "artists" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "name" varchar NOT NULL,
  "since" timestamp,
  "universal_id" varchar,
  "apple_key" varchar,
  "spotify_key" varchar,
  "line_key" varchar,
  "amazon_key" varchar,
  "youtube_key" varchar,
  "image" varchar,
  "fsp" int DEFAULT 0,
  "status" artist_status
);

CREATE TABLE "user_artist" (
  "user_id" uuid,
  "artist_id" uuid,
  PRIMARY KEY ("user_id", "artist_id")
);

CREATE TABLE "products" (
  "upc" varchar PRIMARY KEY,
  "title" varchar NOT NULL
);

CREATE TABLE "tracks" (
  "isrc" varchar PRIMARY KEY
);

CREATE TABLE "product_track" (
  "upc" varchar,
  "isrc" varchar,
  PRIMARY KEY ("upc", "isrc")
);

CREATE TABLE "plays_daily" (
  "isrc" varchar,
  "date" date,
  "spotify" int,
  "apple" int,
  "line" int,
  "amazon" int,
  "youtube" int,
  "sum" int,
  PRIMARY KEY ("isrc", "date")
);

CREATE TABLE "plays_monthly" (
  "isrc" varchar,
  "month" date,
  "spotify" int,
  "apple" int,
  "line" int,
  "amazon" int,
  "youtube" int,
  "sum" int,
  PRIMARY KEY ("isrc", "month")
);

CREATE TABLE "plays_yearly" (
  "isrc" varchar,
  "year" varchar,
  "spotify" int,
  "apple" int,
  "line" int,
  "amazon" int,
  "youtube" int,
  "sum" int,
  PRIMARY KEY ("isrc", "year")
);

CREATE TABLE "indicators" (
  "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "messages" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "room_id" uuid,
  "send_by" uuid,
  "recipient" uuid,
  "message" varchar,
  "created_at" timestamp
);

CREATE TABLE "rooms" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid())
);

CREATE TABLE "room_user" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "room_id" uuid,
  "user_id" uuid
);

CREATE INDEX ON "users" ("id");

CREATE INDEX ON "artists" ("id");

COMMENT ON COLUMN "news"."body" IS 'Content of the post';

COMMENT ON COLUMN "artists"."image" IS 'JAN code';

COMMENT ON COLUMN "messages"."recipient" IS 'recipient';

ALTER TABLE "purchase_history" ADD FOREIGN KEY ("event_id") REFERENCES "webhook_stripe" ("event_id");

ALTER TABLE "offers" ADD FOREIGN KEY ("raid_id") REFERENCES "raids" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("offer_id") REFERENCES "offers" ("id");

ALTER TABLE "news" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "short_notes" ADD FOREIGN KEY ("favorite_id") REFERENCES "favorites" ("id");

ALTER TABLE "user_artist" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_artist" ADD FOREIGN KEY ("artist_id") REFERENCES "artists" ("id");

ALTER TABLE "product_track" ADD FOREIGN KEY ("upc") REFERENCES "products" ("upc");

ALTER TABLE "product_track" ADD FOREIGN KEY ("isrc") REFERENCES "tracks" ("isrc");

ALTER TABLE "plays_daily" ADD FOREIGN KEY ("isrc") REFERENCES "tracks" ("isrc");

ALTER TABLE "plays_monthly" ADD FOREIGN KEY ("isrc") REFERENCES "tracks" ("isrc");

ALTER TABLE "plays_yearly" ADD FOREIGN KEY ("isrc") REFERENCES "tracks" ("isrc");

ALTER TABLE "messages" ADD FOREIGN KEY ("room_id") REFERENCES "rooms" ("id");

ALTER TABLE "room_user" ADD FOREIGN KEY ("room_id") REFERENCES "rooms" ("id");

ALTER TABLE "maps" ADD FOREIGN KEY ("following_user_id") REFERENCES "users" ("id");

ALTER TABLE "maps" ADD FOREIGN KEY ("followed_user_id") REFERENCES "users" ("id");

ALTER TABLE "messages" ADD FOREIGN KEY ("recipient") REFERENCES "users" ("id");

ALTER TABLE "messages" ADD FOREIGN KEY ("send_by") REFERENCES "users" ("id");

ALTER TABLE "room_user" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "txs_fsp" ADD FOREIGN KEY ("to") REFERENCES "users" ("id");

ALTER TABLE "txs_fsp" ADD FOREIGN KEY ("from") REFERENCES "users" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "favorites" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "favorites" ADD FOREIGN KEY ("liked_by") REFERENCES "users" ("id");

ALTER TABLE "offers" ADD FOREIGN KEY ("owner") REFERENCES "users" ("id");

ALTER TABLE "raids" ADD FOREIGN KEY ("owner") REFERENCES "users" ("id");

ALTER TABLE "purchase_history" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
