DROP TABLE IF EXISTS "plays_shazam_daily";
DROP TABLE IF EXISTS "plays_youtube_age_daily";
DROP TABLE IF EXISTS "plays_youtube_gender_daily";
DROP TABLE IF EXISTS "plays_youtube_country_daily";
DROP TABLE IF EXISTS "plays_spotify_age_daily";
DROP TABLE IF EXISTS "plays_spotify_gender_daily";
DROP TABLE IF EXISTS "plays_spotify_country_daily";
DROP TABLE IF EXISTS "plays_line_age_daily";
DROP TABLE IF EXISTS "plays_line_gender_daily";
DROP TABLE IF EXISTS "plays_apple_age_daily";
DROP TABLE IF EXISTS "plays_apple_gender_daily";
DROP TABLE IF EXISTS "plays_apple_country_daily";
DROP TABLE IF EXISTS "plays_amazon_country_daily";

CREATE TABLE "plays_amazon_country_daily" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "isrc" varchar NOT NULL,
  "date" date NOT NULL,
  "country_code" varchar NOT NULL,
  "play_count" int,
  CONSTRAINT plays_amazon_country_daily_uk UNIQUE ("isrc", "date", "country_code")
);

CREATE TABLE "plays_apple_country_daily" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "isrc" varchar NOT NULL,
  "date" date NOT NULL,
  "country_code" varchar(2) NOT NULL,
  "play_count" int,
  CONSTRAINT plays_apple_country_daily_uk UNIQUE ("isrc", "date", "country_code")
);

CREATE TABLE "plays_youtube_country_daily" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "isrc" varchar NOT NULL,
  "date" date NOT NULL,
  "country_code" varchar(2) NOT NULL,
  "play_count" int,
  CONSTRAINT plays_youtube_country_daily_uk UNIQUE ("isrc", "date", "country_code")
);

CREATE TABLE "plays_spotify_country_daily" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "isrc" varchar NOT NULL,
  "date" date NOT NULL,
  "country_code" varchar(2) NOT NULL,
  "play_count" int,
  CONSTRAINT plays_spotify_country_daily_uk UNIQUE ("isrc", "date", "country_code")
);

CREATE TABLE "plays_apple_gender_daily" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "isrc" varchar NOT NULL,
  "date" date NOT NULL,
  "gender" varchar NOT NULL,
  "play_count" int,
  CONSTRAINT plays_apple_gender_daily_uk UNIQUE ("isrc", "date", "gender")
);

CREATE TABLE "plays_apple_age_daily" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "isrc" varchar NOT NULL,
  "date" date NOT NULL,
  "age_band" varchar NOT NULL,
  "play_count" int,
  CONSTRAINT plays_apple_age_daily_uk UNIQUE ("isrc", "date", "age_band")
);

CREATE TABLE "plays_line_gender_daily" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "isrc" varchar NOT NULL,
  "date" date NOT NULL,
  "sex" varchar NOT NULL,
  "play_count" int,
  CONSTRAINT plays_line_gender_daily_uk UNIQUE ("isrc", "date", "sex")
);

CREATE TABLE "plays_line_age_daily" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "isrc" varchar NOT NULL,
  "date" date NOT NULL,
  "age_range" varchar NOT NULL,
  "play_count" int,
  CONSTRAINT plays_line_age_daily_uk UNIQUE ("isrc", "date", "age_range")
);

CREATE TABLE "plays_spotify_gender_daily" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "isrc" varchar NOT NULL,
  "date" date NOT NULL,
  "sex" varchar NOT NULL,
  "play_count" int,
  CONSTRAINT plays_spotify_gender_daily_uk UNIQUE ("isrc", "date", "sex")
);

CREATE TABLE "plays_spotify_age_daily" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "isrc" varchar NOT NULL,
  "date" date NOT NULL,
  "age_range" varchar NOT NULL,
  "play_count" int,
  CONSTRAINT plays_spotify_age_daily_uk UNIQUE ("isrc", "date", "age_range")
);

CREATE TABLE "plays_youtube_gender_daily" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "isrc" varchar NOT NULL,
  "date" date NOT NULL,
  "gender" varchar NOT NULL,
  "play_count" int,
  CONSTRAINT plays_youtube_gender_daily_uk UNIQUE ("isrc", "date", "gender")
);

CREATE TABLE "plays_youtube_age_daily" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "isrc" varchar NOT NULL,
  "date" date NOT NULL,
  "age_group" varchar NOT NULL,
  "play_count" int,
  CONSTRAINT plays_youtube_age_daily_uk UNIQUE ("isrc", "date", "age_group")
);

CREATE TABLE "plays_shazam_daily" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "isrc" varchar NOT NULL,
  "date" date NOT NULL,
  "play_count" int,
  CONSTRAINT plays_shazam_daily_uk UNIQUE ("isrc", "date")
);

CREATE INDEX ON "plays_amazon_country_daily" ("isrc", "date");

CREATE INDEX ON "plays_apple_country_daily" ("isrc", "date");

CREATE INDEX ON "plays_youtube_country_daily" ("isrc", "date");

CREATE INDEX ON "plays_spotify_country_daily" ("isrc", "date");

CREATE INDEX ON "plays_apple_gender_daily" ("isrc", "date");

CREATE INDEX ON "plays_apple_age_daily" ("isrc", "date");

CREATE INDEX ON "plays_line_gender_daily" ("isrc", "date");

CREATE INDEX ON "plays_line_age_daily" ("isrc", "date");

CREATE INDEX ON "plays_spotify_gender_daily" ("isrc", "date");

CREATE INDEX ON "plays_spotify_age_daily" ("isrc", "date");

CREATE INDEX ON "plays_youtube_gender_daily" ("isrc", "date");

CREATE INDEX ON "plays_youtube_age_daily" ("isrc", "date");

CREATE INDEX ON "plays_shazam_daily" ("isrc", "date");

ALTER TABLE "plays_amazon_country_daily" ADD FOREIGN KEY ("isrc") REFERENCES "tracks" ("isrc");

ALTER TABLE "plays_apple_country_daily" ADD FOREIGN KEY ("isrc") REFERENCES "tracks" ("isrc");

ALTER TABLE "plays_youtube_country_daily" ADD FOREIGN KEY ("isrc") REFERENCES "tracks" ("isrc");

ALTER TABLE "plays_spotify_country_daily" ADD FOREIGN KEY ("isrc") REFERENCES "tracks" ("isrc");

ALTER TABLE "plays_apple_gender_daily" ADD FOREIGN KEY ("isrc") REFERENCES "tracks" ("isrc");

ALTER TABLE "plays_apple_age_daily" ADD FOREIGN KEY ("isrc") REFERENCES "tracks" ("isrc");

ALTER TABLE "plays_line_gender_daily" ADD FOREIGN KEY ("isrc") REFERENCES "tracks" ("isrc");

ALTER TABLE "plays_line_age_daily" ADD FOREIGN KEY ("isrc") REFERENCES "tracks" ("isrc");

ALTER TABLE "plays_spotify_gender_daily" ADD FOREIGN KEY ("isrc") REFERENCES "tracks" ("isrc");

ALTER TABLE "plays_spotify_age_daily" ADD FOREIGN KEY ("isrc") REFERENCES "tracks" ("isrc");

ALTER TABLE "plays_youtube_gender_daily" ADD FOREIGN KEY ("isrc") REFERENCES "tracks" ("isrc");

ALTER TABLE "plays_youtube_age_daily" ADD FOREIGN KEY ("isrc") REFERENCES "tracks" ("isrc");

ALTER TABLE "plays_shazam_daily" ADD FOREIGN KEY ("isrc") REFERENCES "tracks" ("isrc");
