name: Contract CI
inputs:
  path: 
    description: "CI environment"
    required: true
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 8.10.5
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'pnpm'
        cache-dependency-path: 'services/contract/pnpm-lock.yaml'
    - name: sample
      run: echo ${{ inputs.path }}
      shell: bash
    - name: Install Dependencies
      run: cd ${{ inputs.path }} && pnpm install
      shell: bash
    - name: Hardhat Test
      run: cd ${{ inputs.path }} && pnpm hardhat test --verbose
      shell: bash
    - name: Hardhat Coverage
      run: cd ${{ inputs.path }} && pnpm hardhat coverage
      shell: bash
