// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint

import 'package:admin/graphql/__generated__/schema.schema.gql.dart'
    show
        GBlockUserInput,
        GContactToAdminInput,
        GCreateNewArtistInput,
        GCreateNewMessageRoomInput,
        GCreateNewOfferInput,
        GCreateNewPrizeInput,
        GCreateNewTransactionInput,
        GCreateNewUserDataInput,
        GCreateQuestInput,
        GDeleteCreditInput,
        GDeleteOfferInput,
        GDeletePortfolioInput,
        GExchangePrizeInput,
        GJSONObject,
        GMarkAsAdminInput,
        GMarkAsMemberInput,
        GMarkAsReadInput,
        GRegisterCreditInput,
        GRegisterInfo,
        GRegisterPortfolioInput,
        GRegisterReleases,
        GReleaseData,
        GReportOfferInput,
        GReportUserInput,
        GRequestPrizeInput,
        GRequestToAccessArtistInput,
        GSearchOptionsOffersInput,
        GSearchProductsQuery,
        GSearchTracksQuery,
        GSendMessageInput,
        GStatusUser,
        GTransactionDirection,
        GUpdateArtistInput,
        GUpdateBelongsToArtistStatusInput,
        GUpdateCreditInput,
        GUpdateOfferInput,
        GUpdateOfferStatusInput,
        GUpdatePortfolioInput,
        GUpdateProductInput,
        GUpdateTrackInput,
        GUpdateUserDataInput,
        GUsePrizeInput;
import 'package:admin/graphql/mutation/__generated__/mutation.data.gql.dart'
    show
        GCreateNewMessageRoomData,
        GCreateNewMessageRoomData_createNewMessageRoom,
        GCreateNewOfferData,
        GCreateNewOfferData_createNewOffer,
        GDeleteOfferData,
        GDeleteOfferData_deleteOffer,
        GSendMessageData,
        GSendMessageData_sendMessage,
        GUpdateOfferInfoData,
        GUpdateOfferInfoData_updateOfferInfo;
import 'package:admin/graphql/mutation/__generated__/mutation.req.gql.dart'
    show
        GCreateNewMessageRoomReq,
        GCreateNewOfferReq,
        GDeleteOfferReq,
        GSendMessageReq,
        GUpdateOfferInfoReq;
import 'package:admin/graphql/mutation/__generated__/mutation.var.gql.dart'
    show
        GCreateNewMessageRoomVars,
        GCreateNewOfferVars,
        GDeleteOfferVars,
        GSendMessageVars,
        GUpdateOfferInfoVars;
import 'package:admin/graphql/query/__generated__/query.data.gql.dart'
    show
        GGetMessageRoomsData,
        GGetMessageRoomsData_getMessageRooms,
        GGetMessageRoomsData_getMessageRooms_messageRoomList,
        GGetMessagesByMessageRoomIdData,
        GGetMessagesByMessageRoomIdData_getMessagesByMessageRoomId,
        GGetMessagesByMessageRoomIdData_getMessagesByMessageRoomId_messageList,
        GGetMessagesByMessageRoomIdData_getMessagesByMessageRoomId_to,
        GGetNotificationsData,
        GGetNotificationsData_getNotifications,
        GGetOffersData,
        GGetOffersData_getOffers,
        GGetOffersData_getOffers_offerList,
        GGetUserDataData,
        GGetUserDataData_getUserData,
        GHealthCheckData,
        GHealthCheckData_healthCheck;
import 'package:admin/graphql/query/__generated__/query.req.gql.dart'
    show
        GGetMessageRoomsReq,
        GGetMessagesByMessageRoomIdReq,
        GGetNotificationsReq,
        GGetOffersReq,
        GGetUserDataReq,
        GHealthCheckReq;
import 'package:admin/graphql/query/__generated__/query.var.gql.dart'
    show
        GGetMessageRoomsVars,
        GGetMessagesByMessageRoomIdVars,
        GGetNotificationsVars,
        GGetOffersVars,
        GGetUserDataVars,
        GHealthCheckVars;
import 'package:built_collection/built_collection.dart';
import 'package:built_value/serializer.dart';
import 'package:built_value/standard_json_plugin.dart' show StandardJsonPlugin;
import 'package:ferry_exec/ferry_exec.dart';
import 'package:gql_code_builder/src/serializers/operation_serializer.dart'
    show OperationSerializer;

part 'serializers.gql.g.dart';

final SerializersBuilder _serializersBuilder = _$serializers.toBuilder()
  ..add(OperationSerializer())
  ..addPlugin(StandardJsonPlugin());
@SerializersFor([
  GBlockUserInput,
  GContactToAdminInput,
  GCreateNewArtistInput,
  GCreateNewMessageRoomData,
  GCreateNewMessageRoomData_createNewMessageRoom,
  GCreateNewMessageRoomInput,
  GCreateNewMessageRoomReq,
  GCreateNewMessageRoomVars,
  GCreateNewOfferData,
  GCreateNewOfferData_createNewOffer,
  GCreateNewOfferInput,
  GCreateNewOfferReq,
  GCreateNewOfferVars,
  GCreateNewPrizeInput,
  GCreateNewTransactionInput,
  GCreateNewUserDataInput,
  GCreateQuestInput,
  GDeleteCreditInput,
  GDeleteOfferData,
  GDeleteOfferData_deleteOffer,
  GDeleteOfferInput,
  GDeleteOfferReq,
  GDeleteOfferVars,
  GDeletePortfolioInput,
  GExchangePrizeInput,
  GGetMessageRoomsData,
  GGetMessageRoomsData_getMessageRooms,
  GGetMessageRoomsData_getMessageRooms_messageRoomList,
  GGetMessageRoomsReq,
  GGetMessageRoomsVars,
  GGetMessagesByMessageRoomIdData,
  GGetMessagesByMessageRoomIdData_getMessagesByMessageRoomId,
  GGetMessagesByMessageRoomIdData_getMessagesByMessageRoomId_messageList,
  GGetMessagesByMessageRoomIdData_getMessagesByMessageRoomId_to,
  GGetMessagesByMessageRoomIdReq,
  GGetMessagesByMessageRoomIdVars,
  GGetNotificationsData,
  GGetNotificationsData_getNotifications,
  GGetNotificationsReq,
  GGetNotificationsVars,
  GGetOffersData,
  GGetOffersData_getOffers,
  GGetOffersData_getOffers_offerList,
  GGetOffersReq,
  GGetOffersVars,
  GGetUserDataData,
  GGetUserDataData_getUserData,
  GGetUserDataReq,
  GGetUserDataVars,
  GHealthCheckData,
  GHealthCheckData_healthCheck,
  GHealthCheckReq,
  GHealthCheckVars,
  GJSONObject,
  GMarkAsAdminInput,
  GMarkAsMemberInput,
  GMarkAsReadInput,
  GRegisterCreditInput,
  GRegisterInfo,
  GRegisterPortfolioInput,
  GRegisterReleases,
  GReleaseData,
  GReportOfferInput,
  GReportUserInput,
  GRequestPrizeInput,
  GRequestToAccessArtistInput,
  GSearchOptionsOffersInput,
  GSearchProductsQuery,
  GSearchTracksQuery,
  GSendMessageData,
  GSendMessageData_sendMessage,
  GSendMessageInput,
  GSendMessageReq,
  GSendMessageVars,
  GStatusUser,
  GTransactionDirection,
  GUpdateArtistInput,
  GUpdateBelongsToArtistStatusInput,
  GUpdateCreditInput,
  GUpdateOfferInfoData,
  GUpdateOfferInfoData_updateOfferInfo,
  GUpdateOfferInfoReq,
  GUpdateOfferInfoVars,
  GUpdateOfferInput,
  GUpdateOfferStatusInput,
  GUpdatePortfolioInput,
  GUpdateProductInput,
  GUpdateTrackInput,
  GUpdateUserDataInput,
  GUsePrizeInput,
])
final Serializers serializers = _serializersBuilder.build();
