//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use super::sea_orm_active_enums::ArtistStatus;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "artists")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub display_name_jp: String,
    pub display_name_en: String,
    pub display_name_kana: Option<String>,
    pub img_url: Option<String>,
    pub fsp: i32,
    pub status: ArtistStatus,
    pub since: Option<Date>,
    pub universal_id: Option<String>,
    pub apple_key: Option<String>,
    pub spotify_key: Option<String>,
    pub line_key: Option<String>,
    pub amazon_key: Option<String>,
    pub youtube_key: Option<String>,
    #[sea_orm(unique)]
    pub artist_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::products::Entity")]
    Products,
    #[sea_orm(has_many = "super::tracks::Entity")]
    Tracks,
    #[sea_orm(has_many = "super::user_artist::Entity")]
    UserArtist,
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Products.def()
    }
}

impl Related<super::tracks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tracks.def()
    }
}

impl Related<super::user_artist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserArtist.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
