//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "exchange_prize_history")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub prize_id: i32,
    pub user: String,
    pub point_used: i32,
    pub amount: i32,
    pub exchanged_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::prizes::Entity",
        from = "Column::PrizeId",
        to = "super::prizes::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Prizes,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::User",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::prizes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Prizes.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
