//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "gender_gen_playback")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub isrc: String,
    pub date: Date,
    pub gender: Option<String>,
    pub age: Option<String>,
    pub play_count: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
