//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use super::sea_orm_active_enums::OfferCategory;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "offers")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "custom(\"ulid\")")]
    pub id: String,
    #[sea_orm(column_type = "custom(\"ulid\")", nullable)]
    pub raid_id: Option<String>,
    pub owner: Option<Uuid>,
    pub release_dt: DateTime,
    pub title: Option<String>,
    pub description: Option<String>,
    pub category: Option<OfferCategory>,
    pub fee: i32,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::comments::Entity")]
    Comments,
    #[sea_orm(
        belongs_to = "super::raids::Entity",
        from = "Column::RaidId",
        to = "super::raids::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Raids,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::Owner",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::comments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Comments.def()
    }
}

impl Related<super::raids::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Raids.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
