//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "offer_attach")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub offer_id: i32,
    pub file_uri: Option<String>,
    pub image_uri: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::offers::Entity",
        from = "Column::OfferId",
        to = "super::offers::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Offers,
}

impl Related<super::offers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Offers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
