//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use super::sea_orm_active_enums::OfferCategory;
use super::sea_orm_active_enums::UserCategory;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "offers")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub raid_id: Option<i32>,
    pub owner: String,
    pub title: String,
    pub description: String,
    pub deadline: DateTime,
    pub place: String,
    pub attention: Option<String>,
    pub required_skill: Option<String>,
    pub target_role: Option<UserCategory>,
    pub img_url: Option<String>,
    pub publicity: bool,
    pub category: Option<OfferCategory>,
    pub fee: i32,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::comments::Entity")]
    Comments,
    #[sea_orm(has_many = "super::offer_attach::Entity")]
    OfferAttach,
    #[sea_orm(has_many = "super::offer_user::Entity")]
    OfferUser,
    #[sea_orm(
        belongs_to = "super::raids::Entity",
        from = "Column::RaidId",
        to = "super::raids::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Raids,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::Owner",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::comments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Comments.def()
    }
}

impl Related<super::offer_attach::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OfferAttach.def()
    }
}

impl Related<super::offer_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OfferUser.def()
    }
}

impl Related<super::raids::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Raids.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::offer_user::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::offer_user::Relation::Offers.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
