//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "plays_yearly")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub isrc: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub year: String,
    pub spotify: Option<i32>,
    pub apple: Option<i32>,
    pub line: Option<i32>,
    pub amazon: Option<i32>,
    pub youtube: Option<i32>,
    pub sum: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tracks::Entity",
        from = "Column::Isrc",
        to = "super::tracks::Column::Isrc",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Tracks,
}

impl Related<super::tracks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tracks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
