//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "prizes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub img_url: Option<String>,
    pub name: String,
    pub point: i32,
    pub description: String,
    pub representation: String,
    pub condition: Option<String>,
    pub publicity: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::exchange_prize_history::Entity")]
    ExchangePrizeHistory,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::Representation",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::exchange_prize_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExchangePrizeHistory.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
