//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "products")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub upc: String,
    pub title: String,
    pub img_url: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::product_track::Entity")]
    ProductTrack,
}

impl Related<super::product_track::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductTrack.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
