//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use super::sea_orm_active_enums::PurchaseStatus;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "purchase_history")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub purchase_id: Uuid,
    pub event_id: Option<i32>,
    pub user_id: Option<Uuid>,
    pub product_id: Option<String>,
    pub amount: Option<i32>,
    pub currency: Option<i32>,
    pub payment_method: Option<String>,
    pub status: Option<PurchaseStatus>,
    pub timestamp: Option<DateTime>,
    pub stripe_payment_intent_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
    #[sea_orm(
        belongs_to = "super::webhook_stripe::Entity",
        from = "Column::EventId",
        to = "super::webhook_stripe::Column::EventId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    WebhookStripe,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::webhook_stripe::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WebhookStripe.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
