//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use super::sea_orm_active_enums::MessageRoomType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "rooms")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub r#type: MessageRoomType,
    pub created_at: DateTime,
    pub latest_sent_at: Option<DateTime>,
    pub latest_message_id: Option<Uuid>,
    pub latest_message: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::messages::Entity",
        from = "Column::LatestMessageId",
        to = "super::messages::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Messages,
    #[sea_orm(has_many = "super::room_user::Entity")]
    RoomUser,
}

impl Related<super::messages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Messages.def()
    }
}

impl Related<super::room_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RoomUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
