//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "artist_status")]
pub enum ArtistStatus {
    #[sea_orm(string_value = "hidden")]
    Hidden,
    #[sea_orm(string_value = "unknown")]
    Unknown,
    #[sea_orm(string_value = "visible")]
    Visible,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "offer_category")]
pub enum OfferCategory {
    #[sea_orm(string_value = "creation")]
    Creation,
    #[sea_orm(string_value = "event")]
    Event,
    #[sea_orm(string_value = "other")]
    Other,
    #[sea_orm(string_value = "promotion")]
    Promotion,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "purchase_status")]
pub enum PurchaseStatus {
    #[sea_orm(string_value = "fail")]
    Fail,
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "success")]
    Success,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "user_category")]
pub enum UserCategory {
    #[sea_orm(string_value = "creater")]
    Creater,
    #[sea_orm(string_value = "curator")]
    Curator,
    #[sea_orm(string_value = "musician")]
    Musician,
    #[sea_orm(string_value = "supporter")]
    Supporter,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "user_status")]
pub enum UserStatus {
    #[sea_orm(string_value = "invited")]
    Invited,
    #[sea_orm(string_value = "joined")]
    Joined,
    #[sea_orm(string_value = "rejected")]
    Rejected,
}
