//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tracks")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub isrc: String,
    pub img_url: Option<String>,
    pub title: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::plays_daily::Entity")]
    PlaysDaily,
    #[sea_orm(has_many = "super::plays_monthly::Entity")]
    PlaysMonthly,
    #[sea_orm(has_many = "super::plays_yearly::Entity")]
    PlaysYearly,
    #[sea_orm(has_many = "super::product_track::Entity")]
    ProductTrack,
}

impl Related<super::plays_daily::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlaysDaily.def()
    }
}

impl Related<super::plays_monthly::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlaysMonthly.def()
    }
}

impl Related<super::plays_yearly::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlaysYearly.def()
    }
}

impl Related<super::product_track::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductTrack.def()
    }
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        super::product_track::Relation::Products.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::product_track::Relation::Tracks.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
