//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "track_credits")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub isrc: String,
    pub commit_user: String,
    pub credit_role: Option<String>,
    pub credit_user: Option<String>,
    pub email: Option<String>,
    pub is_invite: Option<bool>,
    pub memo: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tracks::Entity",
        from = "Column::Isrc",
        to = "super::tracks::Column::Isrc",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Tracks,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CommitUser",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::tracks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tracks.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
