//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use super::sea_orm_active_enums::UserRole;
use super::sea_orm_active_enums::UserStatus;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub username: String,
    pub role: Option<UserRole>,
    pub evm_addr: Option<String>,
    pub status: Option<UserStatus>,
    pub invited_by: Option<Uuid>,
    pub fsp: Option<i32>,
    pub credential: Option<i32>,
    pub update_at: Option<DateTime>,
    pub created_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::comments::Entity")]
    Comments,
    #[sea_orm(has_many = "super::news::Entity")]
    News,
    #[sea_orm(has_many = "super::offers::Entity")]
    Offers,
    #[sea_orm(has_many = "super::purchase_history::Entity")]
    PurchaseHistory,
    #[sea_orm(has_many = "super::raids::Entity")]
    Raids,
    #[sea_orm(has_many = "super::room_user::Entity")]
    RoomUser,
    #[sea_orm(has_many = "super::user_artist::Entity")]
    UserArtist,
}

impl Related<super::comments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Comments.def()
    }
}

impl Related<super::news::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::News.def()
    }
}

impl Related<super::offers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Offers.def()
    }
}

impl Related<super::purchase_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PurchaseHistory.def()
    }
}

impl Related<super::raids::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Raids.def()
    }
}

impl Related<super::room_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RoomUser.def()
    }
}

impl Related<super::user_artist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserArtist.def()
    }
}

impl Related<super::artists::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_artist::Relation::Artists.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_artist::Relation::Users.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
