//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use super::sea_orm_active_enums::OfferCategory;
use super::sea_orm_active_enums::UserCategory;
use super::sea_orm_active_enums::UserStatus;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub id_token: Option<String>,
    pub fcm_token: Option<String>,
    pub username: String,
    pub realname: String,
    pub email: String,
    pub img_url: Option<String>,
    pub evm_addr: Option<String>,
    pub status: UserStatus,
    pub invited_by: Option<String>,
    pub fsp: i32,
    pub fsp_temp: i32,
    pub credential: i32,
    pub category: UserCategory,
    pub primary_category: UserCategory,
    pub is_superadmin: Option<bool>,
    pub publicity: bool,
    pub greeting: Option<String>,
    pub skill: Option<String>,
    pub x_handle: Option<String>,
    pub instagram_handle: Option<String>,
    pub fb_handle: Option<String>,
    pub interest_offer: Option<OfferCategory>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub last_login_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::comments::Entity")]
    Comments,
    #[sea_orm(has_many = "super::exchange_prize_history::Entity")]
    ExchangePrizeHistory,
    #[sea_orm(has_many = "super::invitations::Entity")]
    Invitations,
    #[sea_orm(has_many = "super::messages::Entity")]
    Messages,
    #[sea_orm(has_many = "super::news::Entity")]
    News,
    #[sea_orm(has_many = "super::notification_user::Entity")]
    NotificationUser,
    #[sea_orm(has_many = "super::offer_user::Entity")]
    OfferUser,
    #[sea_orm(has_many = "super::offers::Entity")]
    Offers,
    #[sea_orm(has_many = "super::portfolios::Entity")]
    Portfolios,
    #[sea_orm(has_many = "super::prizes::Entity")]
    Prizes,
    #[sea_orm(has_many = "super::purchase_history::Entity")]
    PurchaseHistory,
    #[sea_orm(has_many = "super::raids::Entity")]
    Raids,
    #[sea_orm(has_many = "super::room_user::Entity")]
    RoomUser,
    #[sea_orm(has_many = "super::track_credits::Entity")]
    TrackCredits,
    #[sea_orm(has_many = "super::user_artist::Entity")]
    UserArtist,
}

impl Related<super::comments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Comments.def()
    }
}

impl Related<super::exchange_prize_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExchangePrizeHistory.def()
    }
}

impl Related<super::invitations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Invitations.def()
    }
}

impl Related<super::messages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Messages.def()
    }
}

impl Related<super::news::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::News.def()
    }
}

impl Related<super::notification_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotificationUser.def()
    }
}

impl Related<super::offer_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OfferUser.def()
    }
}

impl Related<super::offers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Offers.def()
    }
}

impl Related<super::portfolios::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Portfolios.def()
    }
}

impl Related<super::prizes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Prizes.def()
    }
}

impl Related<super::purchase_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PurchaseHistory.def()
    }
}

impl Related<super::raids::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Raids.def()
    }
}

impl Related<super::room_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RoomUser.def()
    }
}

impl Related<super::track_credits::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TrackCredits.def()
    }
}

impl Related<super::user_artist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserArtist.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
