//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "webhook_stripe")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub event_id: i32,
    pub payload: Option<Json>,
    pub timestamp: Option<DateTime>,
    pub processed: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::purchase_history::Entity")]
    PurchaseHistory,
}

impl Related<super::purchase_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PurchaseHistory.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
