FROM rust:1.83.0 AS builder
WORKDIR /app
COPY . .
RUN cargo build --release --package server-extension

FROM gcr.io/distroless/cc-debian12
COPY --from=builder /app/target/release/server-extension /
EXPOSE 8080
CMD ["./server-extension"]
