--
-- PostgreSQL database dump
--

\restrict JeKcY61ieDn04ZeEDEarqZoTyiWItwFpy5Jk8bZgFGRCtBX7WZwmTYyOpEBlQvQ

-- Dumped from database version 15.17
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: artist_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.artist_status AS ENUM (
    'visible',
    'hidden',
    'unknown'
);


--
-- Name: message_room_type; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.message_room_type AS ENUM (
    'dm',
    'group'
);


--
-- Name: offer_category; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.offer_category AS ENUM (
    'creation',
    'event',
    'promotion',
    'other'
);


--
-- Name: offer_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.offer_status AS ENUM (
    'applied',
    'rejected',
    'ongoing',
    'suspend',
    'finished',
    'canceled'
);


--
-- Name: purchase_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.purchase_status AS ENUM (
    'success',
    'fail',
    'pending'
);


--
-- Name: user_artist_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.user_artist_status AS ENUM (
    'accept',
    'reject',
    'check'
);


--
-- Name: user_category; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.user_category AS ENUM (
    'musician',
    'curator',
    'creator',
    'supporter'
);


--
-- Name: user_role; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.user_role AS ENUM (
    'admin',
    'member'
);


--
-- Name: user_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.user_status AS ENUM (
    'invited',
    'rejected',
    'joined'
);


--
-- Name: update_plays_daily_sum(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.update_plays_daily_sum() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  NEW.sum := NEW.spotify + NEW.apple + NEW.line + NEW.amazon + NEW.youtube;
  RETURN NEW;
END;
$$;


--
-- Name: update_plays_monthly_sum(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.update_plays_monthly_sum() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  NEW.sum := NEW.spotify + NEW.apple + NEW.line + NEW.amazon + NEW.youtube;
  RETURN NEW;
END;
$$;


--
-- Name: update_plays_yearly_sum(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.update_plays_yearly_sum() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  NEW.sum := NEW.spotify + NEW.apple + NEW.line + NEW.amazon + NEW.youtube;
  RETURN NEW;
END;
$$;


SET default_table_access_method = heap;

--
-- Name: artists; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.artists (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    display_name_jp character varying NOT NULL,
    display_name_en character varying NOT NULL,
    display_name_kana character varying,
    img_url character varying,
    fsp integer DEFAULT 0 NOT NULL,
    status public.artist_status NOT NULL,
    since date,
    universal_id character varying,
    apple_key character varying,
    spotify_key character varying,
    line_key character varying,
    amazon_key character varying,
    youtube_key character varying,
    artist_id character varying(28)
);


--
-- Name: COLUMN artists.img_url; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.artists.img_url IS 'JAN code';


--
-- Name: comments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comments (
    id integer NOT NULL,
    commented_user_id character varying(28) NOT NULL,
    offer_id integer NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    content character varying NOT NULL
);


--
-- Name: exchange_prize_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.exchange_prize_history (
    id integer NOT NULL,
    prize_id integer NOT NULL,
    "user" character varying(28) NOT NULL,
    point_used integer NOT NULL,
    amount integer DEFAULT 1 NOT NULL,
    exchanged_at timestamp without time zone DEFAULT now() NOT NULL,
    is_used boolean DEFAULT false NOT NULL,
    used_at timestamp without time zone,
    is_requested boolean DEFAULT false NOT NULL,
    requested_at timestamp without time zone
);


--
-- Name: exchange_prize_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.exchange_prize_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exchange_prize_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: favorites; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.favorites (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id character varying(28) NOT NULL,
    liked_by character varying(28) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: gender_gen_playback; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.gender_gen_playback (
    id integer NOT NULL,
    isrc character varying NOT NULL,
    date date NOT NULL,
    gender character varying,
    age character varying,
    play_count integer DEFAULT 0 NOT NULL
);


--
-- Name: gender_gen_playback_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.gender_gen_playback ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gender_gen_playback_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: indicators; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.indicators (
    id smallint NOT NULL,
    name character varying NOT NULL,
    description character varying(140),
    logic character varying NOT NULL
);


--
-- Name: indicators_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.indicators ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.indicators_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invitations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.invitations (
    id integer NOT NULL,
    invitee character varying(28) NOT NULL,
    inviter character varying(28) NOT NULL,
    digest_code character varying,
    invited_at timestamp without time zone DEFAULT now() NOT NULL,
    is_joined boolean DEFAULT false NOT NULL,
    joined_email character varying,
    joined_at timestamp without time zone
);


--
-- Name: invitations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.invitations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invitations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: maps; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.maps (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    following_user_id character varying(28) NOT NULL,
    followed_user_id character varying(28) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: message_attach; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.message_attach (
    id integer NOT NULL,
    sender character varying(28),
    message_id uuid,
    attached_img_url character varying,
    attached_file_url character varying,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone
);


--
-- Name: message_attach_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.message_attach ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.message_attach_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.messages (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    room_id uuid NOT NULL,
    send_by character varying(28) NOT NULL,
    message character varying DEFAULT ''::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: news; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.news (
    id integer NOT NULL,
    title character varying NOT NULL,
    contents text NOT NULL,
    user_id character varying(28),
    category character varying,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: news_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.news ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.news_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notification_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notification_user (
    id integer NOT NULL,
    notification_id integer NOT NULL,
    "user" character varying(28) NOT NULL,
    is_read boolean DEFAULT false NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL
);


--
-- Name: notification_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notification_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    id integer NOT NULL,
    title character varying NOT NULL,
    content character varying NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    category character varying DEFAULT 'info'::character varying
);


--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: offer_attach; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.offer_attach (
    id integer NOT NULL,
    offer_id integer NOT NULL,
    file_uri character varying,
    image_uri character varying
);


--
-- Name: offer_attach_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.offer_attach ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.offer_attach_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: offer_report; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.offer_report (
    id integer NOT NULL,
    offer_id integer NOT NULL,
    reporter_user_id character varying(28) NOT NULL,
    report_content character varying NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: offer_report_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.offer_report ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.offer_report_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: offer_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.offer_user (
    id integer NOT NULL,
    offer_id integer NOT NULL,
    user_id character varying(28) NOT NULL,
    status public.offer_status NOT NULL
);


--
-- Name: offer_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.offer_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.offer_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: offers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.offers (
    id integer NOT NULL,
    raid_id integer,
    owner character varying(28) NOT NULL,
    title character varying NOT NULL,
    description character varying NOT NULL,
    deadline character varying,
    place character varying NOT NULL,
    attention character varying,
    required_skill character varying,
    target_role public.user_category,
    img_url character varying,
    publicity boolean DEFAULT true NOT NULL,
    category public.offer_category,
    fee integer DEFAULT 0 NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: offers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.offers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.offers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plays_amazon_country_daily; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plays_amazon_country_daily (
    id integer NOT NULL,
    isrc character varying NOT NULL,
    date date NOT NULL,
    country_code character varying NOT NULL,
    play_count integer NOT NULL
);


--
-- Name: plays_amazon_country_daily_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.plays_amazon_country_daily ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plays_amazon_country_daily_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plays_apple_age_daily; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plays_apple_age_daily (
    id integer NOT NULL,
    isrc character varying NOT NULL,
    date date NOT NULL,
    age_band character varying NOT NULL,
    play_count integer
);


--
-- Name: plays_apple_age_daily_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.plays_apple_age_daily ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plays_apple_age_daily_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plays_apple_country_daily; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plays_apple_country_daily (
    id integer NOT NULL,
    isrc character varying NOT NULL,
    date date NOT NULL,
    country_code character varying(2) NOT NULL,
    play_count integer
);


--
-- Name: plays_apple_country_daily_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.plays_apple_country_daily ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plays_apple_country_daily_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plays_apple_gender_daily; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plays_apple_gender_daily (
    id integer NOT NULL,
    isrc character varying NOT NULL,
    date date NOT NULL,
    gender character varying NOT NULL,
    play_count integer
);


--
-- Name: plays_apple_gender_daily_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.plays_apple_gender_daily ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plays_apple_gender_daily_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plays_daily; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plays_daily (
    id integer NOT NULL,
    isrc character varying,
    date date,
    spotify integer DEFAULT 0 NOT NULL,
    apple integer DEFAULT 0 NOT NULL,
    line integer DEFAULT 0 NOT NULL,
    amazon integer DEFAULT 0 NOT NULL,
    youtube integer DEFAULT 0 NOT NULL,
    sum integer
);


--
-- Name: plays_daily_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.plays_daily ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plays_daily_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plays_line_age_daily; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plays_line_age_daily (
    id integer NOT NULL,
    isrc character varying NOT NULL,
    date date NOT NULL,
    age_range character varying NOT NULL,
    play_count integer NOT NULL
);


--
-- Name: plays_line_age_daily_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.plays_line_age_daily ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plays_line_age_daily_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plays_line_gender_daily; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plays_line_gender_daily (
    id integer NOT NULL,
    isrc character varying NOT NULL,
    date date NOT NULL,
    sex character varying NOT NULL,
    play_count integer NOT NULL
);


--
-- Name: plays_line_gender_daily_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.plays_line_gender_daily ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plays_line_gender_daily_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plays_monthly; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plays_monthly (
    id integer NOT NULL,
    isrc character varying,
    month date,
    spotify integer DEFAULT 0 NOT NULL,
    apple integer DEFAULT 0 NOT NULL,
    line integer DEFAULT 0 NOT NULL,
    amazon integer DEFAULT 0 NOT NULL,
    youtube integer DEFAULT 0 NOT NULL,
    sum integer
);


--
-- Name: plays_monthly_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.plays_monthly ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plays_monthly_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plays_shazam_daily; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plays_shazam_daily (
    id integer NOT NULL,
    isrc character varying NOT NULL,
    date date NOT NULL,
    play_count integer
);


--
-- Name: plays_shazam_daily_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.plays_shazam_daily ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plays_shazam_daily_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plays_spotify_age_daily; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plays_spotify_age_daily (
    id integer NOT NULL,
    isrc character varying NOT NULL,
    date date NOT NULL,
    age_range character varying NOT NULL,
    play_count integer NOT NULL
);


--
-- Name: plays_spotify_age_daily_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.plays_spotify_age_daily ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plays_spotify_age_daily_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plays_spotify_country_daily; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plays_spotify_country_daily (
    id integer NOT NULL,
    isrc character varying NOT NULL,
    date date NOT NULL,
    country_code character varying(2) NOT NULL,
    play_count integer NOT NULL
);


--
-- Name: plays_spotify_country_daily_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.plays_spotify_country_daily ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plays_spotify_country_daily_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plays_spotify_gender_daily; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plays_spotify_gender_daily (
    id integer NOT NULL,
    isrc character varying NOT NULL,
    date date NOT NULL,
    sex character varying NOT NULL,
    play_count integer NOT NULL
);


--
-- Name: plays_spotify_gender_daily_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.plays_spotify_gender_daily ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plays_spotify_gender_daily_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plays_yearly; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plays_yearly (
    id integer NOT NULL,
    isrc character varying,
    year character varying,
    spotify integer DEFAULT 0 NOT NULL,
    apple integer DEFAULT 0 NOT NULL,
    line integer DEFAULT 0 NOT NULL,
    amazon integer DEFAULT 0 NOT NULL,
    youtube integer DEFAULT 0 NOT NULL,
    sum integer
);


--
-- Name: plays_yearly_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.plays_yearly ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plays_yearly_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plays_youtube_age_daily; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plays_youtube_age_daily (
    id integer NOT NULL,
    isrc character varying NOT NULL,
    date date NOT NULL,
    age_group character varying NOT NULL,
    play_count numeric NOT NULL
);


--
-- Name: plays_youtube_age_daily_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.plays_youtube_age_daily ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plays_youtube_age_daily_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plays_youtube_country_daily; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plays_youtube_country_daily (
    id integer NOT NULL,
    isrc character varying NOT NULL,
    date date NOT NULL,
    country_code character varying(2) NOT NULL,
    play_count numeric NOT NULL
);


--
-- Name: plays_youtube_country_daily_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.plays_youtube_country_daily ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plays_youtube_country_daily_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plays_youtube_gender_daily; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plays_youtube_gender_daily (
    id integer NOT NULL,
    isrc character varying NOT NULL,
    date date NOT NULL,
    gender character varying NOT NULL,
    play_count numeric NOT NULL
);


--
-- Name: plays_youtube_gender_daily_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.plays_youtube_gender_daily ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plays_youtube_gender_daily_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: portfolios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.portfolios (
    id integer NOT NULL,
    user_id character varying(28) NOT NULL,
    title character varying NOT NULL,
    description character varying NOT NULL,
    img_url character varying,
    category character varying NOT NULL,
    release_date date,
    external_url character varying,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: portfolios_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.portfolios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.portfolios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: prizes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.prizes (
    id integer NOT NULL,
    img_url character varying,
    name character varying NOT NULL,
    point integer NOT NULL,
    description character varying NOT NULL,
    representation character varying(28) NOT NULL,
    condition character varying,
    publicity boolean DEFAULT true NOT NULL
);


--
-- Name: COLUMN prizes.condition; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.prizes.condition IS '条件（月件までなど）';


--
-- Name: prizes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.prizes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prizes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_track; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_track (
    id integer NOT NULL,
    upc character varying NOT NULL,
    isrc character varying NOT NULL,
    track_no integer
);


--
-- Name: product_track_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product_track ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_track_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products (
    upc character varying NOT NULL,
    title character varying NOT NULL,
    img_url character varying,
    type character varying,
    artist_id character varying(28),
    distributed_at date
);


--
-- Name: purchase_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.purchase_history (
    purchase_id uuid DEFAULT gen_random_uuid() NOT NULL,
    event_id integer,
    user_id character varying(28) NOT NULL,
    amount integer DEFAULT 0 NOT NULL,
    payment_method character varying,
    status public.purchase_status,
    "timestamp" timestamp without time zone DEFAULT now() NOT NULL,
    stripe_payment_intent_id character varying
);


--
-- Name: quest_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.quest_user (
    id integer NOT NULL,
    "user" character varying(28) NOT NULL,
    quest integer NOT NULL,
    is_done boolean DEFAULT false NOT NULL
);


--
-- Name: quest_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.quest_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quest_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: quests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.quests (
    id integer NOT NULL,
    name character varying NOT NULL,
    description character varying NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    category character varying,
    point integer DEFAULT 0 NOT NULL
);


--
-- Name: quests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.quests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: raids; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.raids (
    id integer NOT NULL,
    owner character varying(28) NOT NULL,
    title character varying NOT NULL,
    description character varying NOT NULL,
    category public.offer_category NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: raids_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.raids ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.raids_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: release_report; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.release_report (
    id integer NOT NULL,
    release character varying NOT NULL,
    reporter_user_id character varying(28) NOT NULL,
    report_content character varying NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: release_report_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.release_report ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.release_report_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: room_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.room_user (
    id integer NOT NULL,
    room_id uuid NOT NULL,
    user_id character varying(28) NOT NULL,
    last_read_message_id uuid
);


--
-- Name: room_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.room_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.room_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rooms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rooms (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    type public.message_room_type DEFAULT 'dm'::public.message_room_type NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    latest_sent_at timestamp without time zone,
    latest_message_id uuid,
    latest_message character varying
);


--
-- Name: short_notes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.short_notes (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    comment character varying(140) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    writer character varying(28) NOT NULL,
    to_user character varying(28) NOT NULL
);


--
-- Name: track_credits; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.track_credits (
    id integer NOT NULL,
    isrc character varying NOT NULL,
    commit_user character varying(28) NOT NULL,
    credit_role character varying,
    credit_user character varying(28),
    email character varying,
    is_invite boolean,
    memo character varying,
    credit_name character varying NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: track_credits_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.track_credits ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.track_credits_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tracks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tracks (
    isrc character varying NOT NULL,
    img_url character varying,
    title character varying NOT NULL,
    artist_id character varying(28)
);


--
-- Name: txs_fsp; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.txs_fsp (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    "from" character varying(28),
    "to" character varying(28) NOT NULL,
    amount integer DEFAULT 0 NOT NULL,
    tx_at timestamp without time zone DEFAULT now() NOT NULL,
    notes character varying
);


--
-- Name: COLUMN txs_fsp.notes; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.txs_fsp.notes IS '摘要';


--
-- Name: user_artist; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_artist (
    id integer NOT NULL,
    user_id character varying(28) NOT NULL,
    is_admin boolean DEFAULT false NOT NULL,
    status public.user_artist_status DEFAULT 'check'::public.user_artist_status NOT NULL,
    artist_id character varying(28) NOT NULL
);


--
-- Name: user_artist_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_artist ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_artist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_blocks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_blocks (
    id integer NOT NULL,
    blocked_user_id character varying(28) NOT NULL,
    blocker_user_id character varying(28) NOT NULL,
    is_solved boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: user_blocks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_blocks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_blocks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_report; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_report (
    id integer NOT NULL,
    reported_user_id character varying(28) NOT NULL,
    reporter_user_id character varying(28) NOT NULL,
    report_content character varying NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: user_report_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_report ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_report_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id character varying(28) NOT NULL,
    id_token character varying,
    username character varying NOT NULL,
    email character varying NOT NULL,
    img_url character varying,
    evm_addr character varying,
    status public.user_status DEFAULT 'invited'::public.user_status NOT NULL,
    invited_by character varying(28),
    fsp integer DEFAULT 0 NOT NULL,
    fsp_temp integer DEFAULT 0 NOT NULL,
    credential integer DEFAULT 0 NOT NULL,
    category public.user_category NOT NULL,
    primary_category public.user_category NOT NULL,
    publicity boolean DEFAULT true NOT NULL,
    greeting character varying,
    skill character varying,
    x_handle character varying,
    instagram_handle character varying,
    fb_handle character varying,
    interest_offer public.offer_category,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    is_superadmin boolean DEFAULT false NOT NULL,
    realname character varying(255) DEFAULT ''::character varying NOT NULL,
    last_login_at timestamp without time zone,
    fcm_token character varying
);


--
-- Name: COLUMN users.id_token; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.users.id_token IS 'Token from firebase auth';


--
-- Name: webhook_stripe; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.webhook_stripe (
    event_id integer NOT NULL,
    payload json,
    "timestamp" timestamp without time zone DEFAULT now() NOT NULL,
    processed boolean DEFAULT false NOT NULL
);


--
-- Name: webhook_stripe_event_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.webhook_stripe ALTER COLUMN event_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.webhook_stripe_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: artists artists_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.artists
    ADD CONSTRAINT artists_pkey PRIMARY KEY (id);


--
-- Name: comments comments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);


--
-- Name: exchange_prize_history exchange_prize_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exchange_prize_history
    ADD CONSTRAINT exchange_prize_history_pkey PRIMARY KEY (id);


--
-- Name: favorites favorites_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorites
    ADD CONSTRAINT favorites_pkey PRIMARY KEY (id);


--
-- Name: gender_gen_playback gender_gen_playback_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.gender_gen_playback
    ADD CONSTRAINT gender_gen_playback_pkey PRIMARY KEY (id);


--
-- Name: indicators indicators_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.indicators
    ADD CONSTRAINT indicators_pkey PRIMARY KEY (id);


--
-- Name: invitations invitations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invitations
    ADD CONSTRAINT invitations_pkey PRIMARY KEY (id);


--
-- Name: maps maps_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.maps
    ADD CONSTRAINT maps_pkey PRIMARY KEY (id);


--
-- Name: message_attach message_attach_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message_attach
    ADD CONSTRAINT message_attach_pkey PRIMARY KEY (id);


--
-- Name: messages messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);


--
-- Name: news news_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.news
    ADD CONSTRAINT news_pkey PRIMARY KEY (id);


--
-- Name: notification_user notification_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_user
    ADD CONSTRAINT notification_user_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: offer_attach offer_attach_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.offer_attach
    ADD CONSTRAINT offer_attach_pkey PRIMARY KEY (id);


--
-- Name: offer_report offer_report_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.offer_report
    ADD CONSTRAINT offer_report_pkey PRIMARY KEY (id);


--
-- Name: offer_user offer_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.offer_user
    ADD CONSTRAINT offer_user_pkey PRIMARY KEY (id);


--
-- Name: offers offers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.offers
    ADD CONSTRAINT offers_pkey PRIMARY KEY (id);


--
-- Name: plays_amazon_country_daily plays_amazon_country_daily_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_amazon_country_daily
    ADD CONSTRAINT plays_amazon_country_daily_pkey PRIMARY KEY (id);


--
-- Name: plays_amazon_country_daily plays_amazon_country_daily_uk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_amazon_country_daily
    ADD CONSTRAINT plays_amazon_country_daily_uk UNIQUE (isrc, date, country_code);


--
-- Name: plays_apple_age_daily plays_apple_age_daily_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_apple_age_daily
    ADD CONSTRAINT plays_apple_age_daily_pkey PRIMARY KEY (id);


--
-- Name: plays_apple_age_daily plays_apple_age_daily_uk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_apple_age_daily
    ADD CONSTRAINT plays_apple_age_daily_uk UNIQUE (isrc, date, age_band);


--
-- Name: plays_apple_country_daily plays_apple_country_daily_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_apple_country_daily
    ADD CONSTRAINT plays_apple_country_daily_pkey PRIMARY KEY (id);


--
-- Name: plays_apple_country_daily plays_apple_country_daily_uk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_apple_country_daily
    ADD CONSTRAINT plays_apple_country_daily_uk UNIQUE (isrc, date, country_code);


--
-- Name: plays_apple_gender_daily plays_apple_gender_daily_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_apple_gender_daily
    ADD CONSTRAINT plays_apple_gender_daily_pkey PRIMARY KEY (id);


--
-- Name: plays_apple_gender_daily plays_apple_gender_daily_uk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_apple_gender_daily
    ADD CONSTRAINT plays_apple_gender_daily_uk UNIQUE (isrc, date, gender);


--
-- Name: plays_daily plays_daily_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_daily
    ADD CONSTRAINT plays_daily_pkey PRIMARY KEY (id);


--
-- Name: plays_line_age_daily plays_line_age_daily_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_line_age_daily
    ADD CONSTRAINT plays_line_age_daily_pkey PRIMARY KEY (id);


--
-- Name: plays_line_age_daily plays_line_age_daily_uk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_line_age_daily
    ADD CONSTRAINT plays_line_age_daily_uk UNIQUE (isrc, date, age_range);


--
-- Name: plays_line_gender_daily plays_line_gender_daily_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_line_gender_daily
    ADD CONSTRAINT plays_line_gender_daily_pkey PRIMARY KEY (id);


--
-- Name: plays_line_gender_daily plays_line_gender_daily_uk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_line_gender_daily
    ADD CONSTRAINT plays_line_gender_daily_uk UNIQUE (isrc, date, sex);


--
-- Name: plays_monthly plays_monthly_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_monthly
    ADD CONSTRAINT plays_monthly_pkey PRIMARY KEY (id);


--
-- Name: plays_shazam_daily plays_shazam_daily_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_shazam_daily
    ADD CONSTRAINT plays_shazam_daily_pkey PRIMARY KEY (id);


--
-- Name: plays_shazam_daily plays_shazam_daily_uk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_shazam_daily
    ADD CONSTRAINT plays_shazam_daily_uk UNIQUE (isrc, date);


--
-- Name: plays_spotify_age_daily plays_spotify_age_daily_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_spotify_age_daily
    ADD CONSTRAINT plays_spotify_age_daily_pkey PRIMARY KEY (id);


--
-- Name: plays_spotify_age_daily plays_spotify_age_daily_uk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_spotify_age_daily
    ADD CONSTRAINT plays_spotify_age_daily_uk UNIQUE (isrc, date, age_range);


--
-- Name: plays_spotify_country_daily plays_spotify_country_daily_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_spotify_country_daily
    ADD CONSTRAINT plays_spotify_country_daily_pkey PRIMARY KEY (id);


--
-- Name: plays_spotify_country_daily plays_spotify_country_daily_uk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_spotify_country_daily
    ADD CONSTRAINT plays_spotify_country_daily_uk UNIQUE (isrc, date, country_code);


--
-- Name: plays_spotify_gender_daily plays_spotify_gender_daily_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_spotify_gender_daily
    ADD CONSTRAINT plays_spotify_gender_daily_pkey PRIMARY KEY (id);


--
-- Name: plays_spotify_gender_daily plays_spotify_gender_daily_uk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_spotify_gender_daily
    ADD CONSTRAINT plays_spotify_gender_daily_uk UNIQUE (isrc, date, sex);


--
-- Name: plays_yearly plays_yearly_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_yearly
    ADD CONSTRAINT plays_yearly_pkey PRIMARY KEY (id);


--
-- Name: plays_youtube_age_daily plays_youtube_age_daily_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_youtube_age_daily
    ADD CONSTRAINT plays_youtube_age_daily_pkey PRIMARY KEY (id);


--
-- Name: plays_youtube_age_daily plays_youtube_age_daily_uk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_youtube_age_daily
    ADD CONSTRAINT plays_youtube_age_daily_uk UNIQUE (isrc, date, age_group);


--
-- Name: plays_youtube_country_daily plays_youtube_country_daily_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_youtube_country_daily
    ADD CONSTRAINT plays_youtube_country_daily_pkey PRIMARY KEY (id);


--
-- Name: plays_youtube_country_daily plays_youtube_country_daily_uk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_youtube_country_daily
    ADD CONSTRAINT plays_youtube_country_daily_uk UNIQUE (isrc, date, country_code);


--
-- Name: plays_youtube_gender_daily plays_youtube_gender_daily_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_youtube_gender_daily
    ADD CONSTRAINT plays_youtube_gender_daily_pkey PRIMARY KEY (id);


--
-- Name: plays_youtube_gender_daily plays_youtube_gender_daily_uk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_youtube_gender_daily
    ADD CONSTRAINT plays_youtube_gender_daily_uk UNIQUE (isrc, date, gender);


--
-- Name: portfolios portfolios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.portfolios
    ADD CONSTRAINT portfolios_pkey PRIMARY KEY (id);


--
-- Name: prizes prizes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prizes
    ADD CONSTRAINT prizes_pkey PRIMARY KEY (id);


--
-- Name: product_track product_track_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_track
    ADD CONSTRAINT product_track_pkey PRIMARY KEY (id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (upc);


--
-- Name: purchase_history purchase_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchase_history
    ADD CONSTRAINT purchase_history_pkey PRIMARY KEY (purchase_id);


--
-- Name: quest_user quest_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quest_user
    ADD CONSTRAINT quest_user_pkey PRIMARY KEY (id);


--
-- Name: quests quests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quests
    ADD CONSTRAINT quests_pkey PRIMARY KEY (id);


--
-- Name: raids raids_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.raids
    ADD CONSTRAINT raids_pkey PRIMARY KEY (id);


--
-- Name: release_report release_report_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.release_report
    ADD CONSTRAINT release_report_pkey PRIMARY KEY (id);


--
-- Name: room_user room_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room_user
    ADD CONSTRAINT room_user_pkey PRIMARY KEY (id);


--
-- Name: rooms rooms_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT rooms_pkey PRIMARY KEY (id);


--
-- Name: short_notes short_notes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.short_notes
    ADD CONSTRAINT short_notes_pkey PRIMARY KEY (id);


--
-- Name: track_credits track_credits_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.track_credits
    ADD CONSTRAINT track_credits_pkey PRIMARY KEY (id);


--
-- Name: tracks tracks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tracks
    ADD CONSTRAINT tracks_pkey PRIMARY KEY (isrc);


--
-- Name: txs_fsp txs_fsp_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.txs_fsp
    ADD CONSTRAINT txs_fsp_pkey PRIMARY KEY (id);


--
-- Name: artists unique_artist_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.artists
    ADD CONSTRAINT unique_artist_id UNIQUE (artist_id);


--
-- Name: user_artist user_artist_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_artist
    ADD CONSTRAINT user_artist_pkey PRIMARY KEY (id);


--
-- Name: user_blocks user_blocks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_blocks
    ADD CONSTRAINT user_blocks_pkey PRIMARY KEY (id);


--
-- Name: user_report user_report_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_report
    ADD CONSTRAINT user_report_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: webhook_stripe webhook_stripe_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.webhook_stripe
    ADD CONSTRAINT webhook_stripe_pkey PRIMARY KEY (event_id);


--
-- Name: comments_commented_user_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX comments_commented_user_id_idx ON public.comments USING btree (commented_user_id);


--
-- Name: comments_offer_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX comments_offer_id_idx ON public.comments USING btree (offer_id);


--
-- Name: exchange_prize_history_user_is_used_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX exchange_prize_history_user_is_used_idx ON public.exchange_prize_history USING btree ("user", is_used);


--
-- Name: favorites_liked_by_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX favorites_liked_by_idx ON public.favorites USING btree (liked_by);


--
-- Name: favorites_user_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX favorites_user_id_idx ON public.favorites USING btree (user_id);


--
-- Name: gender_gen_playback_isrc_date_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX gender_gen_playback_isrc_date_idx ON public.gender_gen_playback USING btree (isrc, date);


--
-- Name: idx_artist_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_artist_id ON public.artists USING btree (artist_id);


--
-- Name: idx_plays_daily_isrc_date_covering; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_plays_daily_isrc_date_covering ON public.plays_daily USING btree (isrc, date) INCLUDE (sum, spotify, apple, line, amazon, youtube);


--
-- Name: idx_product_track_upc_isrc_track_no_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_product_track_upc_isrc_track_no_id ON public.product_track USING btree (upc, isrc, track_no, id);


--
-- Name: idx_products_artist_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_products_artist_id ON public.products USING btree (artist_id);


--
-- Name: maps_followed_user_id_following_user_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX maps_followed_user_id_following_user_id_idx ON public.maps USING btree (followed_user_id, following_user_id);


--
-- Name: maps_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX maps_id_idx ON public.maps USING btree (id);


--
-- Name: messages_room_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX messages_room_id_idx ON public.messages USING btree (room_id);


--
-- Name: messages_send_by_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX messages_send_by_idx ON public.messages USING btree (send_by);


--
-- Name: notification_user_user_notification_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX notification_user_user_notification_id_idx ON public.notification_user USING btree ("user", notification_id);


--
-- Name: offer_user_offer_id_user_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX offer_user_offer_id_user_id_idx ON public.offer_user USING btree (offer_id, user_id);


--
-- Name: offers_owner_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX offers_owner_idx ON public.offers USING btree (owner);


--
-- Name: plays_amazon_country_daily_isrc_date_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX plays_amazon_country_daily_isrc_date_idx ON public.plays_amazon_country_daily USING btree (isrc, date);


--
-- Name: plays_apple_age_daily_isrc_date_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX plays_apple_age_daily_isrc_date_idx ON public.plays_apple_age_daily USING btree (isrc, date);


--
-- Name: plays_apple_country_daily_isrc_date_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX plays_apple_country_daily_isrc_date_idx ON public.plays_apple_country_daily USING btree (isrc, date);


--
-- Name: plays_apple_gender_daily_isrc_date_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX plays_apple_gender_daily_isrc_date_idx ON public.plays_apple_gender_daily USING btree (isrc, date);


--
-- Name: plays_daily_isrc_date_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX plays_daily_isrc_date_idx ON public.plays_daily USING btree (isrc, date);


--
-- Name: plays_line_age_daily_isrc_date_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX plays_line_age_daily_isrc_date_idx ON public.plays_line_age_daily USING btree (isrc, date);


--
-- Name: plays_line_gender_daily_isrc_date_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX plays_line_gender_daily_isrc_date_idx ON public.plays_line_gender_daily USING btree (isrc, date);


--
-- Name: plays_monthly_isrc_month_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX plays_monthly_isrc_month_idx ON public.plays_monthly USING btree (isrc, month);


--
-- Name: plays_shazam_daily_isrc_date_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX plays_shazam_daily_isrc_date_idx ON public.plays_shazam_daily USING btree (isrc, date);


--
-- Name: plays_spotify_age_daily_isrc_date_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX plays_spotify_age_daily_isrc_date_idx ON public.plays_spotify_age_daily USING btree (isrc, date);


--
-- Name: plays_spotify_country_daily_isrc_date_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX plays_spotify_country_daily_isrc_date_idx ON public.plays_spotify_country_daily USING btree (isrc, date);


--
-- Name: plays_spotify_gender_daily_isrc_date_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX plays_spotify_gender_daily_isrc_date_idx ON public.plays_spotify_gender_daily USING btree (isrc, date);


--
-- Name: plays_yearly_isrc_year_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX plays_yearly_isrc_year_idx ON public.plays_yearly USING btree (isrc, year);


--
-- Name: plays_youtube_age_daily_isrc_date_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX plays_youtube_age_daily_isrc_date_idx ON public.plays_youtube_age_daily USING btree (isrc, date);


--
-- Name: plays_youtube_country_daily_isrc_date_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX plays_youtube_country_daily_isrc_date_idx ON public.plays_youtube_country_daily USING btree (isrc, date);


--
-- Name: plays_youtube_gender_daily_isrc_date_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX plays_youtube_gender_daily_isrc_date_idx ON public.plays_youtube_gender_daily USING btree (isrc, date);


--
-- Name: portfolios_user_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX portfolios_user_id_idx ON public.portfolios USING btree (user_id);


--
-- Name: prizes_representation_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX prizes_representation_idx ON public.prizes USING btree (representation);


--
-- Name: product_track_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX product_track_id_idx ON public.product_track USING btree (id);


--
-- Name: product_track_upc_isrc_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX product_track_upc_isrc_idx ON public.product_track USING btree (upc, isrc);


--
-- Name: quest_user_user_quest_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX quest_user_user_quest_idx ON public.quest_user USING btree ("user", quest);


--
-- Name: raids_owner_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX raids_owner_idx ON public.raids USING btree (owner);


--
-- Name: room_user_room_id_user_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX room_user_room_id_user_id_idx ON public.room_user USING btree (room_id, user_id);


--
-- Name: short_notes_id_created_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX short_notes_id_created_at_idx ON public.short_notes USING btree (id, created_at);


--
-- Name: track_credits_isrc_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX track_credits_isrc_idx ON public.track_credits USING btree (isrc);


--
-- Name: txs_fsp_from_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX txs_fsp_from_idx ON public.txs_fsp USING btree ("from");


--
-- Name: txs_fsp_id_tx_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX txs_fsp_id_tx_at_idx ON public.txs_fsp USING btree (id, tx_at);


--
-- Name: txs_fsp_to_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX txs_fsp_to_idx ON public.txs_fsp USING btree ("to");


--
-- Name: user_artist_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_artist_id_idx ON public.user_artist USING btree (id);


--
-- Name: users_evm_addr_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_evm_addr_idx ON public.users USING btree (evm_addr);


--
-- Name: comments comments_commented_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_commented_user_id_fkey FOREIGN KEY (commented_user_id) REFERENCES public.users(id);


--
-- Name: comments comments_offer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_offer_id_fkey FOREIGN KEY (offer_id) REFERENCES public.offers(id);


--
-- Name: exchange_prize_history exchange_prize_history_prize_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exchange_prize_history
    ADD CONSTRAINT exchange_prize_history_prize_id_fkey FOREIGN KEY (prize_id) REFERENCES public.prizes(id);


--
-- Name: exchange_prize_history exchange_prize_history_user_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exchange_prize_history
    ADD CONSTRAINT exchange_prize_history_user_fkey FOREIGN KEY ("user") REFERENCES public.users(id);


--
-- Name: favorites favorites_liked_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorites
    ADD CONSTRAINT favorites_liked_by_fkey FOREIGN KEY (liked_by) REFERENCES public.users(id);


--
-- Name: favorites favorites_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorites
    ADD CONSTRAINT favorites_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: invitations invitations_invitee_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invitations
    ADD CONSTRAINT invitations_invitee_fkey FOREIGN KEY (invitee) REFERENCES public.users(id);


--
-- Name: invitations invitations_inviter_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invitations
    ADD CONSTRAINT invitations_inviter_fkey FOREIGN KEY (inviter) REFERENCES public.users(id);


--
-- Name: maps maps_followed_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.maps
    ADD CONSTRAINT maps_followed_user_id_fkey FOREIGN KEY (followed_user_id) REFERENCES public.users(id);


--
-- Name: maps maps_following_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.maps
    ADD CONSTRAINT maps_following_user_id_fkey FOREIGN KEY (following_user_id) REFERENCES public.users(id);


--
-- Name: message_attach message_attach_message_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message_attach
    ADD CONSTRAINT message_attach_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.messages(id);


--
-- Name: messages messages_room_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.rooms(id);


--
-- Name: messages messages_send_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_send_by_fkey FOREIGN KEY (send_by) REFERENCES public.users(id);


--
-- Name: news news_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.news
    ADD CONSTRAINT news_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: notification_user notification_user_notification_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_user
    ADD CONSTRAINT notification_user_notification_id_fkey FOREIGN KEY (notification_id) REFERENCES public.notifications(id);


--
-- Name: notification_user notification_user_user_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_user
    ADD CONSTRAINT notification_user_user_fkey FOREIGN KEY ("user") REFERENCES public.users(id);


--
-- Name: offer_attach offer_attach_offer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.offer_attach
    ADD CONSTRAINT offer_attach_offer_id_fkey FOREIGN KEY (offer_id) REFERENCES public.offers(id);


--
-- Name: offer_user offer_user_offer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.offer_user
    ADD CONSTRAINT offer_user_offer_id_fkey FOREIGN KEY (offer_id) REFERENCES public.offers(id);


--
-- Name: offer_user offer_user_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.offer_user
    ADD CONSTRAINT offer_user_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: offers offers_owner_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.offers
    ADD CONSTRAINT offers_owner_fkey FOREIGN KEY (owner) REFERENCES public.users(id);


--
-- Name: offers offers_raid_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.offers
    ADD CONSTRAINT offers_raid_id_fkey FOREIGN KEY (raid_id) REFERENCES public.raids(id);


--
-- Name: plays_amazon_country_daily plays_amazon_country_daily_isrc_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_amazon_country_daily
    ADD CONSTRAINT plays_amazon_country_daily_isrc_fkey FOREIGN KEY (isrc) REFERENCES public.tracks(isrc);


--
-- Name: plays_apple_age_daily plays_apple_age_daily_isrc_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_apple_age_daily
    ADD CONSTRAINT plays_apple_age_daily_isrc_fkey FOREIGN KEY (isrc) REFERENCES public.tracks(isrc);


--
-- Name: plays_apple_country_daily plays_apple_country_daily_isrc_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_apple_country_daily
    ADD CONSTRAINT plays_apple_country_daily_isrc_fkey FOREIGN KEY (isrc) REFERENCES public.tracks(isrc);


--
-- Name: plays_apple_gender_daily plays_apple_gender_daily_isrc_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_apple_gender_daily
    ADD CONSTRAINT plays_apple_gender_daily_isrc_fkey FOREIGN KEY (isrc) REFERENCES public.tracks(isrc);


--
-- Name: plays_daily plays_daily_isrc_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_daily
    ADD CONSTRAINT plays_daily_isrc_fkey FOREIGN KEY (isrc) REFERENCES public.tracks(isrc);


--
-- Name: plays_line_age_daily plays_line_age_daily_isrc_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_line_age_daily
    ADD CONSTRAINT plays_line_age_daily_isrc_fkey FOREIGN KEY (isrc) REFERENCES public.tracks(isrc);


--
-- Name: plays_line_gender_daily plays_line_gender_daily_isrc_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_line_gender_daily
    ADD CONSTRAINT plays_line_gender_daily_isrc_fkey FOREIGN KEY (isrc) REFERENCES public.tracks(isrc);


--
-- Name: plays_monthly plays_monthly_isrc_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_monthly
    ADD CONSTRAINT plays_monthly_isrc_fkey FOREIGN KEY (isrc) REFERENCES public.tracks(isrc);


--
-- Name: plays_shazam_daily plays_shazam_daily_isrc_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_shazam_daily
    ADD CONSTRAINT plays_shazam_daily_isrc_fkey FOREIGN KEY (isrc) REFERENCES public.tracks(isrc);


--
-- Name: plays_spotify_age_daily plays_spotify_age_daily_isrc_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_spotify_age_daily
    ADD CONSTRAINT plays_spotify_age_daily_isrc_fkey FOREIGN KEY (isrc) REFERENCES public.tracks(isrc);


--
-- Name: plays_spotify_country_daily plays_spotify_country_daily_isrc_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_spotify_country_daily
    ADD CONSTRAINT plays_spotify_country_daily_isrc_fkey FOREIGN KEY (isrc) REFERENCES public.tracks(isrc);


--
-- Name: plays_spotify_gender_daily plays_spotify_gender_daily_isrc_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_spotify_gender_daily
    ADD CONSTRAINT plays_spotify_gender_daily_isrc_fkey FOREIGN KEY (isrc) REFERENCES public.tracks(isrc);


--
-- Name: plays_yearly plays_yearly_isrc_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_yearly
    ADD CONSTRAINT plays_yearly_isrc_fkey FOREIGN KEY (isrc) REFERENCES public.tracks(isrc);


--
-- Name: plays_youtube_age_daily plays_youtube_age_daily_isrc_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_youtube_age_daily
    ADD CONSTRAINT plays_youtube_age_daily_isrc_fkey FOREIGN KEY (isrc) REFERENCES public.tracks(isrc);


--
-- Name: plays_youtube_country_daily plays_youtube_country_daily_isrc_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_youtube_country_daily
    ADD CONSTRAINT plays_youtube_country_daily_isrc_fkey FOREIGN KEY (isrc) REFERENCES public.tracks(isrc);


--
-- Name: plays_youtube_gender_daily plays_youtube_gender_daily_isrc_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plays_youtube_gender_daily
    ADD CONSTRAINT plays_youtube_gender_daily_isrc_fkey FOREIGN KEY (isrc) REFERENCES public.tracks(isrc);


--
-- Name: portfolios portfolios_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.portfolios
    ADD CONSTRAINT portfolios_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: prizes prizes_representation_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prizes
    ADD CONSTRAINT prizes_representation_fkey FOREIGN KEY (representation) REFERENCES public.users(id);


--
-- Name: product_track product_track_isrc_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_track
    ADD CONSTRAINT product_track_isrc_fkey FOREIGN KEY (isrc) REFERENCES public.tracks(isrc);


--
-- Name: product_track product_track_upc_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_track
    ADD CONSTRAINT product_track_upc_fkey FOREIGN KEY (upc) REFERENCES public.products(upc);


--
-- Name: products products_artist_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_artist_id_fkey FOREIGN KEY (artist_id) REFERENCES public.artists(artist_id);


--
-- Name: purchase_history purchase_history_event_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchase_history
    ADD CONSTRAINT purchase_history_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.webhook_stripe(event_id);


--
-- Name: purchase_history purchase_history_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.purchase_history
    ADD CONSTRAINT purchase_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: raids raids_owner_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.raids
    ADD CONSTRAINT raids_owner_fkey FOREIGN KEY (owner) REFERENCES public.users(id);


--
-- Name: room_user room_user_room_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room_user
    ADD CONSTRAINT room_user_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.rooms(id);


--
-- Name: room_user room_user_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room_user
    ADD CONSTRAINT room_user_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: rooms rooms_latest_message_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT rooms_latest_message_id_fkey FOREIGN KEY (latest_message_id) REFERENCES public.messages(id);


--
-- Name: track_credits track_credits_commit_user_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.track_credits
    ADD CONSTRAINT track_credits_commit_user_fkey FOREIGN KEY (commit_user) REFERENCES public.users(id);


--
-- Name: track_credits track_credits_isrc_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.track_credits
    ADD CONSTRAINT track_credits_isrc_fkey FOREIGN KEY (isrc) REFERENCES public.tracks(isrc);


--
-- Name: tracks tracks_artist_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tracks
    ADD CONSTRAINT tracks_artist_id_fkey FOREIGN KEY (artist_id) REFERENCES public.artists(artist_id);


--
-- Name: txs_fsp txs_fsp_from_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.txs_fsp
    ADD CONSTRAINT txs_fsp_from_fkey FOREIGN KEY ("from") REFERENCES public.users(id);


--
-- Name: txs_fsp txs_fsp_to_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.txs_fsp
    ADD CONSTRAINT txs_fsp_to_fkey FOREIGN KEY ("to") REFERENCES public.users(id);


--
-- Name: user_artist user_artist_artist_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_artist
    ADD CONSTRAINT user_artist_artist_id_fkey FOREIGN KEY (artist_id) REFERENCES public.artists(artist_id);


--
-- Name: user_artist user_artist_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_artist
    ADD CONSTRAINT user_artist_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: user_blocks user_blocks_blocked_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_blocks
    ADD CONSTRAINT user_blocks_blocked_user_id_fkey FOREIGN KEY (blocked_user_id) REFERENCES public.users(id);


--
-- Name: user_blocks user_blocks_blocker_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_blocks
    ADD CONSTRAINT user_blocks_blocker_user_id_fkey FOREIGN KEY (blocker_user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict JeKcY61ieDn04ZeEDEarqZoTyiWItwFpy5Jk8bZgFGRCtBX7WZwmTYyOpEBlQvQ
