name: fsdao

packages:
  - apps/**
  - packages/**

scripts:
  bootstrap:
    run: melos bootstrap
  test:
    run: melos run test
  analyze:
    run: melos exec -- flutter analyze .
    description: analyze flutter codes.
  format: 
    run: melos exec -- dart format .
    description: format dart codes on all packages.
