include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_single_quotes: true

analyzer:
  errors:
    unused_import: ignore
  exclude:
    - lib/data/graphql/__generated__/**
    - lib/data/graphql/mutation/__generated__/**
    - lib/data/graphql/query/__generated__/**
    - lib/data/model/**
