targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: client|lib/data/graphql/schema.graphql
          global_enum_fallbacks: true

      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: client|lib/data/graphql/schema.graphql

      json_serializable:
        options:
          create_field_map: true
          create_per_field_to_json: true
