name: client
description: "A FRIENDSHIP. App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  utils: 
    path: ../../packages/utils
  smooth_page_indicator: ^1.2.0+3
  flutter_native_splash: ^2.4.1
  cupertino_icons: ^1.0.6
  ferry: ^0.15.0+1
  ferry_flutter: ^0.9.0
  gql_http_link: ^1.1.0
  built_collection: ^5.1.1
  flutter_riverpod: ^2.5.1
  hive: ^2.2.3
  ferry_hive_store: ^0.5.2
  hive_flutter: ^1.1.0
  freezed_annotation: ^2.4.4
  flutter_secure_storage: ^9.0.0
  json_annotation: ^4.9.0
  fl_chart: ^0.69.0
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  countries_world_map: ^1.3.0
  flutter_graph_view: ^1.1.3+1
  app_settings: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  ferry_generator: ^0.9.1-dev.2
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/friendshipdao_loop.gif
    - assets/logo_visualonly.jpg
    - assets/friendship_logo_white.png
    - assets/logo_visualonly_dark.jpg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

flutter_native_splash:
  color: '#ffffff'
  image: 'assets/logo_visualonly.jpg'
  color_dark: '#262626'
  image_dark: 'assets/logo_visualonly_dark.jpg'
  fullscreen: true
  android_12:
    icon_background_color: '#ffffff'
    image: 'assets/logo_visualonly.jpg'