name: Backend CI

runs:
  using: "composite"
  steps:
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Install cargo-related tools
      uses: taiki-e/install-action@v2
      with:
        tools: nextest
    - name: Install Dependencies
      run: cd services/backend && cargo build --release
      shell: bash
    - name: Test
      run: cd services/backend && cargo nextest run
      shell: bash
    - name: Clippy
      run: cd services/backend && cargo fmt -- --check
      shell: bash
