name: Next.js CI

inputs:
  path: 
    description: "Path to workspace"
    required: true
  app:
    description: "App to run"
    required: true
  node:
    description: "Node version"
    required: true

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 8.10.5
    - name: Use Node.js ${{ inputs.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node }}
        cache: 'pnpm'
        cache-dependency-path: 'services/frontend/pnpm-lock.yaml'
    - name: Install Dependencies
      run: cd ${{ inputs.path }} && pnpm install
      shell: bash
    - name: Lint
      run: cd ${{ inputs.path }}/${{ inputs.app }} && pnpm lint
      shell: bash
    - name: Build
      run: cd ${{ inputs.path }}/${{ inputs.app }} && pnpm build
      shell: bash
