// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxsXn4qfEelWu8Y0ui90VHRUXGAH8Hz5c',
    appId: '1:23181195188:ios:d0f828c4c06954e57fe4e1',
    messagingSenderId: '23181195188',
    projectId: 'frienda-auth-test1',
    storageBucket: 'frienda-auth-test1.appspot.com',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkYBfsIsL-PALnx6-20rJB1eEGAXMUYF8',
    appId: '1:23181195188:web:594e335e4c124a917fe4e1',
    messagingSenderId: '23181195188',
    projectId: 'frienda-auth-test1',
    authDomain: 'frienda-auth-test1.firebaseapp.com',
    storageBucket: 'frienda-auth-test1.appspot.com',
    measurementId: 'G-KP76ZKNTDP',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ8YeoVrHJih8M1H5VHrJumHC5Ww9kgjA',
    appId: '1:955799892508:web:81817a5f2d973106b125d9',
    messagingSenderId: '955799892508',
    projectId: 'friendship-dao',
    authDomain: 'friendship-dao.firebaseapp.com',
    storageBucket: 'friendship-dao.firebasestorage.app',
    measurementId: 'G-BSD0532YHD',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcBNXUqgoPfdQJ63ut3kwrZmRsoJ-V0ow',
    appId: '1:955799892508:ios:5b5e149135c011f5b125d9',
    messagingSenderId: '955799892508',
    projectId: 'friendship-dao',
    storageBucket: 'friendship-dao.firebasestorage.app',
    iosBundleId: 'com.frienda.client',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5FWV8kjyaJexlDhYlCr35r9hea0ailEk',
    appId: '1:955799892508:android:1813210a68c16c54b125d9',
    messagingSenderId: '955799892508',
    projectId: 'friendship-dao',
    storageBucket: 'friendship-dao.firebasestorage.app',
  );

}