// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxsXn4qfEelWu8Y0ui90VHRUXGAH8Hz5c',
    appId: '1:23181195188:ios:d0f828c4c06954e57fe4e1',
    messagingSenderId: '23181195188',
    projectId: 'frienda-auth-test1',
    storageBucket: 'frienda-auth-test1.appspot.com',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkYBfsIsL-PALnx6-20rJB1eEGAXMUYF8',
    appId: '1:23181195188:web:594e335e4c124a917fe4e1',
    messagingSenderId: '23181195188',
    projectId: 'frienda-auth-test1',
    authDomain: 'frienda-auth-test1.firebaseapp.com',
    storageBucket: 'frienda-auth-test1.appspot.com',
    measurementId: 'G-KP76ZKNTDP',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkYBfsIsL-PALnx6-20rJB1eEGAXMUYF8',
    appId: '1:23181195188:web:c6798ac7cb4e22317fe4e1',
    messagingSenderId: '23181195188',
    projectId: 'frienda-auth-test1',
    authDomain: 'frienda-auth-test1.firebaseapp.com',
    storageBucket: 'frienda-auth-test1.appspot.com',
    measurementId: 'G-64BS7X84PL',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxsXn4qfEelWu8Y0ui90VHRUXGAH8Hz5c',
    appId: '1:23181195188:ios:0607d8d4ffa5636a7fe4e1',
    messagingSenderId: '23181195188',
    projectId: 'frienda-auth-test1',
    storageBucket: 'frienda-auth-test1.appspot.com',
    iosBundleId: 'com.frienda.client',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiIj7IcHQ4a31-rRJBtMW_vSyxWCZYnFQ',
    appId: '1:23181195188:android:52ea4f139c7a11307fe4e1',
    messagingSenderId: '23181195188',
    projectId: 'frienda-auth-test1',
    storageBucket: 'frienda-auth-test1.appspot.com',
  );

}