name: fsdao/Test

on:
  push:
    paths:
      - 'services/backend/**'
      - 'services/frontend/apps/admin/**'
      - 'services/frontend/apps/client/**'
      - 'services/frontend/apps/mobile/**'
      - 'services/contract/**'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'services/backend/**'
      - 'services/frontend/apps/client/**'
      - 'services/frontend/apps/admin/**'
      - 'services/frontend/apps/mobile/**'
      - 'services/contract/**'

jobs:
  backend:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, 'backend')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Rust Test
        uses: ./.github/actions/backend-test
        with:
          path: 'services/backend'


#  admin:
#    runs-on: ubuntu-latest
#    if: |
#      contains(github.event.head_commit.message, 'admin')
#    strategy:
#      matrix:
#        node-version: [18, 20]
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#      - name: Admin Test
#        uses: ./.github/actions/nextjs-test
#        with:
#          path: 'services/frontend'
#          app: 'admin'
#          node: ${{ matrix.node-version }}


  client:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, 'client')
    strategy:
      matrix:
        node-version: [18, 20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Client CI
        uses: ./.github/actions/nextjs-test
        with:
          path: 'services/frontend'
          app: 'client'
          node: ${{ matrix.node-version }}

  contract:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, 'contract')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Contract Test
        uses: ./.github/actions/contract-test
        with:
          path: 'services/contract'