name: Deploy Dev Server

on:
  push:
    branches:
      - main
    paths:
      - 'services/backend/**'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
  IMAGE: ${{ secrets.GCP_IMAGE }}
  REGION: ${{ secrets.GCP_REGION }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  SERVER_NAME: ${{ secrets.SERVER_NAME }}
  SERVICE_ACCOUNT_DSP: ${{ secrets.SERVICE_ACCOUNT_DSP }}
  SCR_SERVICE_ACCOUNT_DSP: ${{ secrets.SCR_SERVICE_ACCOUNT_DSP }}
  ETH_RPC_URL: ${{ secrets.ETH_RPC_URL }}
  CREDENTIAL_CONTRACT_ADDRESS: ${{ secrets.CREDENTIAL_CONTRACT_ADDRESS }}
  DSP_QUERY_DAILY_TEMPLATE: ${{ secrets.DSP_QUERY_DAILY_TEMPLATE }}
  DSP_QUERY_MONTHLY_TEMPLATE: ${{ secrets.DSP_QUERY_MONTHLY_TEMPLATE }}
  SCR_DSP_QUERY_DAILY_TEMPLATE: ${{ secrets.SCR_DSP_QUERY_DAILY_TEMPLATE }}
  LOCATION: ${{ secrets.LOCATION }}
  SCR_LOCATION: ${{ secrets.SCR_LOCATION }}
  DSP_PJ_ID: ${{ secrets.DSP_PJ_ID }}
  SCR_DSP_PJ_ID: ${{ secrets.SCR_DSP_PJ_ID }}
  HASH_SALT: ${{ secrets.HASH_SALT }}
  TAG: latest
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  GENDER_GEN_PLAYBACK_URL: ${{ secrets.GENDER_GEN_PLAYBACK_URL }}
  GENDER_GEN_PLAYBACK_PREFIX: ${{ secrets.GENDER_GEN_PLAYBACK_PREFIX }}
  GENDER_GEN_AUTH_URL: ${{ secrets.GENDER_GEN_AUTH_URL }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

#      - name: Test
#        uses: ./.github/actions/backend-test
#        with:
#          path: 'services/backend'

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCLOUD_AUTH }}"

      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Build
        run: cd services/backend && docker build --platform linux/amd64 -f Dockerfile.server -t asia-northeast1-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME/$IMAGE:$TAG .

      - name: Push
        run: docker push asia-northeast1-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME/$IMAGE:$TAG

      - name: Deploy
        run: gcloud run deploy ${{ secrets.SERVER_NAME }} --image asia-northeast1-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME/$IMAGE:$TAG --region ${{ secrets.GCP_REGION }} --allow-unauthenticated --set-env-vars DATABASE_URL=$DATABASE_URL,GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }},SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }},ENVIRONMENT=dev,SERVICE_ACCOUNT_DSP=$SERVICE_ACCOUNT_DSP,ETH_RPC_URL=$ETH_RPC_URL,CREDENTIAL_CONTRACT_ADDRESS=$CREDENTIAL_CONTRACT_ADDRESS,DSP_QUERY_DAILY_TEMPLATE=$DSP_QUERY_DAILY_TEMPLATE,DSP_QUERY_MONTHLY_TEMPLATE=$DSP_QUERY_MONTHLY_TEMPLATE,LOCATION=$LOCATION,DSP_PJ_ID=$DSP_PJ_ID,HASH_SALT=$HASH_SALT,CLIENT_ID=$CLIENT_ID,CLIENT_SECRET=$CLIENT_SECRET,GENDER_GEN_PLAYBACK_URL=$GENDER_GEN_PLAYBACK_URL,GENDER_GEN_PLAYBACK_PREFIX=$GENDER_GEN_PLAYBACK_PREFIX,GENDER_GEN_AUTH_URL=$GENDER_GEN_AUTH_URL,SCR_DSP_QUERY_DAILY_TEMPLATE=$SCR_DSP_QUERY_DAILY_TEMPLATE,SCR_DSP_PJ_ID=$SCR_DSP_PJ_ID,SCR_SERVICE_ACCOUNT_DSP=$SCR_SERVICE_ACCOUNT_DSP,SCR_LOCATION=$SCR_LOCATION