name: Deploy Prd Server

on:
  push:
    branches:
      - release
    paths:
      - 'services/backend/**'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID_PRD }}
  SERVICE_NAME: ${{ secrets.SERVICE_NAME_PRD }}
  IMAGE: ${{ secrets.GCP_IMAGE_PRD }}
  REGION: ${{ secrets.GCP_REGION_PRD }}
  DATABASE_URL: ${{ secrets.DATABASE_URL_PRD }}
  SERVER_NAME: ${{ secrets.SERVER_NAME_PRD }}
  TAG: latest

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

#      - name: Test
#        uses: ./.github/actions/backend-test
#        with:
#          path: 'services/backend'

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCLOUD_AUTH_PRD }}"

      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Build
        run: cd services/backend && docker build --platform linux/amd64 -f Dockerfile.server -t asia-northeast1-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME/$IMAGE:$TAG .

      - name: Push
        run: docker push asia-northeast1-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME/$IMAGE:$TAG

      - name: Deploy
        run: gcloud run deploy ${{ secrets.SERVER_NAME_PRD }} --image asia-northeast1-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME/$IMAGE:$TAG --region ${{ secrets.GCP_REGION_PRD }} --allow-unauthenticated --set-env-vars DATABASE_URL=$DATABASE_URL,GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }},SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}
